### ISSUE TITLE
Team9 Sprint 2 Feature Ticket Past Score Board

### ISSUE THREAD

**Issue by Bohan-is-in-the-zone** [UQdeco2800/2021-ext-studio-2#100]
# **Description**
The past score board: Users can see their history scores and the date they played. 
This board can be opened in game over screen and the screen before start the game. 

A brief diagram representing the classes and files involved in the feature:
![image](https://user-images.githubusercontent.com/24644880/132438284-ae7a0c61-5e2f-4db0-b9c6-4cd4c64843a4.png)
 
## SubFeature/component (optional)
A new screen that can be opened from game over screen and the main screen. 

# **Dependencies**
Team7: Adds their achievment trophies in the record. 
 
 
# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Design the planning diagram for a rudimentary system on miro.
- [x] Create an empty board. Just a new blank interface.
- [x] Create two links that can go to that interface. One is from the main screen. One is from game over screen.
- [x] Implementing the history score system --- the file writer part(store each time score)
- [x] Implementing the history score system --- the file reading part(how to load data and display the scores on the board)
- [x] Add designers' design, make the board beautiful.  
 
**Completion Deadline:** (Date)
11 September
 
# **Members**
(Git hub name)(Slack name)
- @Bohan-is-in-the-zone (Bohan Xu)
- @YiYang200 (Yi Yang)
- @Noarrrr (Keyu Bai)
- @yungseop (YoungSeob Lee)
- @pranavdhoolia (Pranav Dhoolia)

**Comment by uqtnieva** [comment]
Nice! Could you also add in some dates for your milestones, link the dependency tickets and a little bit more description i.e. how can the user access the scoreboard? Why should there be a scoreboard in the game?

**Comment by Bohan-is-in-the-zone** [comment]
ok :)
