### ISSUE TITLE
Team 4 Sprint 2: Task 1 - Design animations for character jumping. (Sept. 7)

### ISSUE THREAD

**Issue by kprohith** [UQdeco2800/2021-ext-studio-2#101]
# **Description**
**Task:** [Designing animations for jumping](#101)
**Feature:** [Team 4 Feature Ticket - Main Player Character](#6)

During the game, the protagonist will encounter various obstacles, and we will design suitable actions for the protagonist to avoid the obstacles. Therefore, the action image of the protagonist jumping will be realized in this task.
 
## **Example (optional)**

- Link up the movements of different levels of characters raising their legs to present the visual effect of the protagonist jumping.
- Make an animation of jumping over obstacles of different heights. At this stage, the jumping animation will temporarily be unified into one display effect.

 
# **Dependencies** 
There are a few tasks that will be the dependencies of this task. 
- [x] The perspective of the game character is affected by the loop mechanism of the game map, and it will only show an animated image that jumps to the right. (#5)
- [x] The appearance of obstacles may affect the image of the character when jumping. (#14)
 
# **Tasks**
Detailed task description.
- [x] Task 1.1: Design frames for each jump action of the character and make sure it is the same size.
- [x] Task 1.2: Connect images to form an atlas, and make jumping animations (Refer to the height of the obstacle to ensure that the effect is unified).
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Task 1.1 (Sept. 7)
- [x] Task 1.2 (Sept. 8)

**Completion Deadline:** Sept. 14

 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Jiacheng Ni - @RecklessPotcover (Alex)
- Jescy Xu - @enmmjc 
- Yingxin Liu - @LIU-Evelyn

**Comment by RecklessPotcover** [comment]
Completed the middle frame of the character jump. @LIU-Evelyn can take this as the reference and complete the rest transition frames.

![main_player_jump_2](https://user-images.githubusercontent.com/31987631/132879038-6c38911e-cc40-442e-a1d2-a5ab1a541bc7.png)

**Comment by LIU-Evelyn** [comment]
Created a jump animation with transition effects
![main_player_jump](https://user-images.githubusercontent.com/88132643/132880512-01086855-51d7-4833-a263-d0e5719ffd4a.png)
