### ISSUE TITLE
Team 4 Sprint 2: Task 2 - Integrate animations for character jumping into the game. (Sept. 9)

### ISSUE THREAD

**Issue by kprohith** [UQdeco2800/2021-ext-studio-2#102]
# **Description**
**Task:** [ Integrate animations for character jumping into the game](#104).
**Feature:** [Main Player Character](#6 )
 
This function is dedicated to the realization of the protagonist's actions performed in the game, integrating the protagonist’s aesthetic image with the respective change in the image when doing actions (Here Jumping). We need to consider the interactions it needs to perform when Jumping, and how this interaction will affect its appearance when moving along the path. Therefore, it is also necessary to determine the different images of the main character due to changes in their Jumping movement (state) during the interaction process. Each image should clearly correspond to the required intervals of jumping state.
 
- [x] Implement movement physics required for jumping movement
- [x] integrate the movement with the procedural map generation/pathway generation component when ready
- [x] Implement character jumping movement animation

# **Dependencies**
- Jumping animation image design. (#101)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 Integrate the jumping animation atlas with the game (Sept. 7)
- [x] Step 2 Implement and adjust the physics of the jumping movement. (Sept. 8)
- [x] Step 3 Implement jumping animation. (Sept. 8)
 
**Completion Deadline:** Sept. 8
 
 
# **Documentation**
[Main Character](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Main-Character)

# **Member**
- Rohith Palakirti (@kprohith)
- Prateek Kumar Gupta (@prateek45)

**Comment by prateek45** [comment]
I have written the description of the #102 task.
