### ISSUE TITLE
Team 4 Sprint 2: Task 3 - Design animations for character crouching. (Sept. 10)

### ISSUE THREAD

**Issue by kprohith** [UQdeco2800/2021-ext-studio-2#103]
# **Description**
**Task:** [Designing animations for crouching](#103)
**Feature:** [Team 4 Feature Ticket - Main Player Character](#6)

During the game, the protagonist will encounter various obstacles, and we will design suitable actions for the protagonist to avoid the obstacles. Therefore, the action image of the protagonist crouching will be realized in this task.
 
## **Example (optional)**

- Design the cohesive effect of the standing and squatting movements of the character, showing how the protagonist avoids obstacles by squatting down.
- At this stage, we will make an initial squat animation based on the lowest squat space to facilitate future improvements.

 
# **Dependencies** 
There are a few tasks that will be the dependencies of this task. 
- [ ] The perspective of the game character is affected by the loop mechanism of the game map, and it will only show an animated image that jumps to the right. (#5)
- [ ] The size of the space under the obstacle will affect the design of the character crouching. (#14)
 
# **Tasks**
Detailed task description.
- [ ] Task 3.1: Design the character's crouching image according to the available crouching space left by obstacles for the protagonist of the game.
- [ ] Task 3.2: Connect images to form an atlas, and make crouching animations (Refer to the height of the space below the obstacle in the air to ensure that the effect is unified).
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Task 3.1 (Sept. 9)
- [ ] Task 3.2 (Sept. 10)

**Completion Deadline:** Sept. 14

 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Jiacheng Ni - @RecklessPotcover (Alex)
- Jescy Xu - @enmmjc 
- Yingxin Liu - @LIU-Evelyn
