### ISSUE TITLE
Team 4 Sprint 2: Task 4 - Integrate animations for character crouching into the game. (Sept. 11)

### ISSUE THREAD

**Issue by kprohith** [UQdeco2800/2021-ext-studio-2#104]
# **Description**
**Task:** [ Integrate animations for character crouching into the game](#104).
**Feature:** [Main Player Character](#6 )
 
This function is dedicated to the realization of the protagonist's actions performed in the game, integrating the protagonist’s aesthetic image with the respective change in the image when doing actions (Here Crouching). We need to consider the interactions it needs to perform when crouching, and how this interaction will affect its appearance when moving along the path. Therefore, it is also necessary to determine the different images of the main character due to changes in their crouching movement (state) during the interaction process. Each image should clearly correspond to the required intervals of crouching state.
 
- [x] Implement movement physics required for crouching movement
- [x] integrate the movement with the procedural map generation/pathway generation component when ready
- [x] Implement character movement animation

# **Dependencies**
- Crouching animation image design. (#103)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 Integrate the crouching animation atlas with the game (Sept. 9)
- [x] Step 2 Implement and adjust the physics of the crouching movement. (Sept. 10)
- [x] Step 3 Implement crouching animation. (Sept. 11)
 
**Completion Deadline:** Sept. 11
 
 
# **Documentation**
[Main Character](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Main-Character)

# **Member**
- Rohith Palakirti (@kprohith)
- Prateek Kumar Gupta (@prateek45)

**Comment by prateek45** [comment]
I have updated the #104 task description
