### ISSUE TITLE
Broken stone animation design

### ISSUE THREAD

**Issue by ShokuJO** [UQdeco2800/2021-ext-studio-2#107]
# **Description**
**Task:** Broken stone animation design (#107 )
**Feature:** Active attacker (#105 )

Design the model of broken stone dropping from the sky and the animation.

# **Dependencies**
- [x] The style of obstacles will based on the map designed(#6)
 
# **Milestones**
- [x] Design the model of broken stone (Sep. 8)
- [x] Finish the animation of broken stone.(Sep. 10) 
 
**Completion Deadline:** Sep.11
 
# **Documentation**
- [Design of Obstacles](../wikis/Obstacles)

 
# **Member**
- JOJO(@ShokuJO) (Guanhao Qiao)
