### ISSUE TITLE
Enemy attack item design 

### ISSUE THREAD

**Issue by HKeG** [UQdeco2800/2021-ext-studio-2#108]
# **Description**
**Task:** [Enemy attack item design](#108 ).
**Feature:** [Active attacker](#105  )

Design enemy attack special effects.
 

# **Dependencies**
- [x] Enemy idle and attack animation design(#109 ) 

 
- [x] Code implementation of remote attack monster(#153 )
# **Milestones**
- [x] Design models of enemy attack item (Sep.8)
- [x] Finish models of enemy attack item (Sep.8)
- [x] Finish the animation of enemy attack item(Sep.10)
 
**Completion Deadline:** Sep.11

# **Documentation**
- [Game Play of Obstacles](../wikis/Obstacles-Gameplay)
- [Design of Obstacles](../wikis/Obstacles)
- [Code Guidelines of Obstacles](Obstacles-Code)
 
# **Member**
- Haoke  (@HKeG ) (Haoke Sheng)
