### ISSUE TITLE
Enemy idle and attack animation design (Sep. 8)

### ISSUE THREAD

**Issue by GavintheLionHeart** [UQdeco2800/2021-ext-studio-2#109]
# **Description**
**Task:** Enemy idle and attack animation design (#10 )
**Feature:** Active attacker (#105 )

Design the enemy's character, and design different animations when the enemy is motionless and attacking.  

# **Dependencies**
- [x] The style of obstacles will based on the map designed(#6)
 
# **Milestones**
- [x] Design the sketch of the enemy (Sep. 9)
- [x] Finish the animation of different enemy status. (Sep. 9) 
 
**Completion Deadline:** Sep.11
 
# **Documentation**
- [Design of Obstacles](../wikis/Obstacles)

 
# **Member**
- He Zhu (GavintheLionHeart) He Zhu
