### ISSUE TITLE
Team 4 Sprint 2: Task 5 - Design player interactions while attacking.  (Sept. 12)

### ISSUE THREAD

**Issue by kprohith** [UQdeco2800/2021-ext-studio-2#111]
# **Description**
**Task:** [Design player interactions while attacking](#111)
**Feature:** [Team 4 Feature Ticket Sprint 2 - Main Player Character Obstacle, Item and Attack Interactions and Animations ](#136)

During the game, the protagonist will encounter various obstacles, and we will design suitable actions for the protagonist to attack the monsters. Therefore, the action image of the protagonist attacking will be finalised in this task.
 
## **Example (optional)**

- Design the cohesive effect of attacking movements of the character, showing how the protagonist fights the monsters.
- At this stage, we will make an initial attacking animation based on attacking to facilitate future improvements.

 
# **Dependencies** 
There are a few tasks that will be the dependencies of this task. 
- [x] The perspective of the game character is affected by the loop mechanism of the game map, in case the monsters will move around and more frames will be needed to be finalised.
- [ ] The size of the weapon and the boundaries of attacking will affect the design of the character.

# **Tasks**
Detailed task description.
- [x] Task 3.1: Design the character's attacking image according to the weapons and the space left for the protagonist to attack.
- [x] Task 3.2: Connect images to form an atlas, and make attack animations.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Task 3.1 (Sept. 11)
- [x] Task 3.2 (Sept. 12)

**Completion Deadline:** Sept. 14

 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Jiacheng Ni - @RecklessPotcover (Alex)
- Jescy Xu - @enmmjc 
- Yingxin Liu - @LIU-Evelyn

**Comment by RecklessPotcover** [comment]
Completed all frames of the character attack.

![main_player_attack_1](https://user-images.githubusercontent.com/31987631/132879410-69e765a6-18a6-493f-88c4-6e276ba701d1.png)
![main_player_attack_2](https://user-images.githubusercontent.com/31987631/132879431-34651636-cb99-4cb9-ba60-7f43117647fb.png)
![main_player_attack_3](https://user-images.githubusercontent.com/31987631/132879438-783b51f3-b98e-44fd-8f36-48428a7511e5.png)
