### ISSUE TITLE
Team 4 Sprint 2: Task 6 - Integrate player interactions while attacking into the game.  (Sept. 13)

### ISSUE THREAD

**Issue by kprohith** [UQdeco2800/2021-ext-studio-2#112]
# **Description**
**Task:** [Integrate player interactions while attacking into the game](#112) 
**Feature:** [Main Player Character Obstacle, Item and Attack Interactions and Animations](#136)
 
- [x] Implement movement physics required for attack actions
- [x] Create the texture atlas required for attack animations
- [x] Implement character attack animation into the game

# **Dependencies**
- Attack animation sprite design. (#112)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 Create the attack animation atlas with the game (Sept. 9)
- [x] Step 2 Implement and adjust the physics of the attack movement. (Sept. 10)
- [x] Step 3 Implement attack animation. (Sept. 11)
 
**Completion Deadline:** Sept. 11
 
 
# **Documentation**
[Main Character](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Main-Character)

# **Member**
- Rohith Palakirti (@kprohith)
- Prateek Kumar Gupta (@prateek45)
