### ISSUE TITLE
Team 6 task 1 - Game background optimization

### ISSUE THREAD

**Issue by yzy98** [UQdeco2800/2021-ext-studio-2#115]
# **Description**
**Task:** [Game background optimization](https://github.com/UQdeco2800/2021-ext-studio-2/issues/115).
**Feature:** [changeable background](https://github.com/UQdeco2800/2021-ext-studio-2/issues/123)
 
Re-design the game background which is changeable during the infinite loop game, finish the implementation
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Re-design the game background (Sep. 7)
- [x] Get feedback from Obstacle team and make changes (Sep. 8)
- [x] Implement the static background (Sep. 10)
- [x] Create auto-generating background mechanism and implement moving background (Sep. 13)
- [x] Unit test (if possible) (Sep. 14)
- [x] Documentation of `Background` updated on wiki (Sep. 15)
 
**Completion Deadline:** Sep. 15
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Zi Yang (@yzy98 ) (Zi Yang)
