### ISSUE TITLE
Team 6 task 2 - Buffer time before starting the game

### ISSUE THREAD

**Issue by yzy98** [UQdeco2800/2021-ext-studio-2#116]
# **Description**
**Task:** [Buffer time before starting the game](https://github.com/UQdeco2800/2021-ext-studio-2/issues/116).
**Feature:** [Buffer time](https://github.com/UQdeco2800/2021-ext-studio-2/issues/124)
 
Implementing buffer time before starting the game.
 
# **Dependencies**
- [ ] Buffer time will not be considered into total game time.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Buffer time interface design (Sep. 7)
- [x] UI implementation (Sep. 9)
- [x] Count down mechanism to start the game (Sep. 13)
- [ ] Unit test (if necessary) and wiki writing (Sep. 14)
 
**Completion Deadline:** Sep. 14
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitLab Username) (Slack Handle)
- Zi Yang (@yzy98) (Zi Yang)
