### ISSUE TITLE
Team 6 Sprint 2 - Feature Ticket - Changeable background

### ISSUE THREAD

**Issue by yzy98** [UQdeco2800/2021-ext-studio-2#123]
# **Description**
With the moving the player, the game background will also change automatically.
  
# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Game background re-design (Sep. 7)
- [ ] Feedback from Obstacle team (Sep. 8)
- [ ] Implement static background to the correct layer (Sep. 10)
- [ ] Create background changing mechanism (Sep. 12)
- [ ] Implement mechanism and unit test if necessary (Sep. 14)
 
**Completion Deadline:** Sep. 14
 
# **Extras (optional)**
- [ ] Add animation effect into background.
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [User documentation](../../wikis/Game-Guide#section1)
- ...
 
# **Members**
- Name (GitLab Username) (Slack Handle) -- only one is needed if they are the same.
- Zi Yang (@yzy98) (Zi Yang)

**Comment by uqtnieva** [comment]
Hey! More detail needs to be in the description e.g. how will it change: will the colour change? Is it a scrolling background? How will it appear in the game: will it start to scroll 5 seconds after starting the game? You also have to mention why this feature should be added. 

List any dependencies and link relevant tickets. If there are no dependencies, please state this.
