### ISSUE TITLE
Team 6 Sprint 2 - Feature Ticket - Design and implement better UI and functionality of Game Over Screen

### ISSUE THREAD

**Issue by EvansH1997** [UQdeco2800/2021-ext-studio-2#125]
# **Description**
**Task:** 
Designing on the new game over screen which includes the 5-second countdown prompt box and the final score. Create a better game overscreen UI and background which more related to the game, make all buttons more neat and aligned.

The current game overscreen is mostly blank white color, have the word " game overscreen " in the middle. There are working " total score", working " click to play " " main menu " buttons but the layout is still messy.
 

# **Dependencies**

- [x] Team2 player status: The game loop will end depending on the health bar when the player is running out of life. 
 (#7 )
- [x] Team9 scoring system: Display the final score on the game over screen (#3 )

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design the new game overscreen background related more to the game itself (Sep.8)
- [x] Implement the new background to the game over screen (Sep.10)
- [x]Fix the layout of all the game over screen,at the same time make the areas, buttons more neat and aligned  (Sep.13 )
- [x] Unit test (if necessary) and wiki writing (Sep. 14)
 
**Completion Deadline:** Sep.15
 
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitLab Username) (Slack Handle)
- Richard (EvansH1997) (Anh Duy Hoang)
-
