### ISSUE TITLE
Team 7 - Major Achievements System Enhancement 

### ISSUE THREAD

**Issue by ThatTechedGuy** [UQdeco2800/2021-ext-studio-2#126]
**Original Feature**: #4 

# **Description**
Enhancing the Achievements Feature.  Add achievement popup animations and sounds. More polished and better looking assets will be added. 

## SubFeature/component (optional)
- Notification sounds for achievement popup cards 
- Better looking trophies and consistent popups
- Dynamically generating popup GUI using libgdx instead of images and labels for better customization. Animating these popups such that they transition into the game area. 
- Integrating bonus score functionality with the scoring system
- Bonus achievement score achievement popup UI 
- Adding additional achievements
 
## **Examples**
- **Notification sounds for achievement popup cards**:   Achievement unlocked! (Play positive feedback sound)
- **Bonus achievement score achievement popup UI**: '+5!' bonus points message near the Scoring system dialog when a Veteran Bronze achievement is unlocked. The corresponding bonus score will then be added to the score.  Temporarily shown for a small period of time. 

# **Dependencies**
- Scoring System Integration #99 
- Item pickup details (name of the item) #9 
   
# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Design Notification Sound (Sept. 4)
- [ ] Integrate achievement notification sound (Sept. 8) 
- [ ] Integrating bonus score functionality with the scoring system (Sept. 8) 
- [ ] Displaying the bonus score popup (Sept. 8)
- [ ] Adding new achievements (Sept. 8)

**Completion Deadline:** Sept. 13

# **Extras (optional)**
- [ ] Trophy redesign
- [ ] Dynamically generating popup GUI using libgdx instead of images and labels for better customization. Animating these popups such that they transition into the game area. 
- [ ] Testing Async Task Queue
 
# **Members**
- Vishal Gupta (@ThatTechedGuy)
- Akshay Varma (@Butcanudothis)
- Zibo Gong (@Zibo1)
- Kai Wang (@Kaiwang4)
- Aditya Singh Cheema (@addiii4)
