### ISSUE TITLE
Team 7 - Achievement Records and Storyline

### ISSUE THREAD

**Issue by ThatTechedGuy** [UQdeco2800/2021-ext-studio-2#127]
**Original Feature**: #4 

# **Description**
The idea is to score the record of achievements for each game in local storage, add a brand new achievements screen which shows locked and unlocked achievements (i.e, achievements which have already been encountered during the game). Achievements will also be displayed with the past score history. 
 
## SubFeature/component (optional)
- Achievements screen with locked and unlocked achievements
- Persistent achievements functionality
- Achievements Screen linked with game story

### Examples
- **Achievements Screen linked with game story**: Chapter is unlocked in the Achievements Screen section.
- **Achievements Screen**:  Displaying locked and unlocked achievements. (Unlocked achievements are grayed out or annotated with a locked icon). 
   
# **Milestones**
- [ ] Achievements Screen Paper Design (Sept. 7) 
- [ ] Achievements Screen Assets (Sept. 8)
- [ ] Storyline Integration with Design Team (Sept. 8)
- [ ] Achievements Screen Final Design (Sept. 9)
- [ ] Persistent Achievements logic (Sept. 10)
- [ ] Coding the Achievements Screen GUI (Sept. 10)
- [ ] Coding unlockable storyline chapters (Sept. 10)
 
**Completion Deadline:** Sept. 13
 
# **Members**
- Vishal Gupta (@ThatTechedGuy)
- Akshay Varma (@Butcanudothis)
- Zibo Gong (@Zibo1)
- Kai Wang (@Kaiwang4)
- Aditya Singh Cheema (@addiii4)

**Comment by uqtnieva** [comment]
Looks good! I noticed that #100 also covers displaying the past scores. Will these be displayed on separate screens? Or the same screen? This is something that could be worth clearing up with team 9.

**Comment by ThatTechedGuy** [comment]
@uqtnieva @Bohan-is-in-the-zone Hey, thanks! 

TL, DR: These will be displayed on separate screens. Let me elaborate.

1. **Achievements Screen:** Displays locked and unlocked achievements. Also showcases locked and unlocked chapters of the game story. Chapter 1 will get unlocked when, say, the user unlocks 5 bronze achievements and so on. 

Note: An achievement can be unlocked multiple times. 

2. **Score History Screen by Team 9**: The plan is to display the score + achievements (and associated bonus points). We will add a button which will provide the detailed score history with list of achievements and their bonus score etc. We are yet to finalize the designs though. We have talked about including the achievements history but we have not finalized the details yet. This is still in the TBD status and may or may not be implemented in this sprint but we will try to start it as the 3rd feature since this is slightly complex and requires a lot of inter team collaboration.

**Comment by Bohan-is-in-the-zone** [comment]
@ThatTechedGuy @Butcanudothis Hey, I just checked your achievment board. That looks really good. May I ask if I can use the same background? This is the current page of ours. 
![image](https://user-images.githubusercontent.com/70745460/132932528-aac2197d-b627-4d83-8f17-baa29f99ff20.png)
Is it ok that we add the same background? I think the color scheme of our board is match with your achivement boxes.

**Comment by Bohan-is-in-the-zone** [comment]
And also a suggestion. The texts are difficult to see. Change them to white will be better 😁
