### ISSUE TITLE
Achievements Screen Assets (Sept. 8)

### ISSUE THREAD

**Issue by ThatTechedGuy** [UQdeco2800/2021-ext-studio-2#129]
**Feature:** #127 

# Description 
To design assets for the Achievements Screen. This includes assets for locked and unlocked chapters, a small game story and a creative background image.  

# Milestones
- [x] Locked chapter icon @Kaiwang4 @Butcanudothis 
- [x] Unlocked Chapter Design:  @Kaiwang4 @Butcanudothis 
       - Unlocked chapter icon 
- [ ] The asset of each chapter @Kaiwang4 
- [x] Achievements Screen background image @Zibo1 . 

# Dependencies 
- **Type of Art**: Pixel Art / Photoshop
- **Software to be used:** PixilArt / Photoshop

# Members
- Akshay Varma (@Butcanudothis)
- Zibo Gong (@Zibo1)
- Kai Wang (@Kaiwang4)
- Aditya Singh Cheema (@addiii4)

**Comment by Zibo1** [comment]
Assets redesigned achievement background

**Comment by Kaiwang4** [comment]
adding chapter art
