### ISSUE TITLE
Random obstacles

### ISSUE THREAD

**Issue by lisslulay** [UQdeco2800/2021-ext-studio-2#14]
# **Description**
This is a function to increase the difficulty of the game. In the course of the game, some obstacles will continue to be generated as time passes. It may be a roadblock or some disaster. Once the character touches these obstacles, this will cause the character to lose a certain amount of blood.

## SubFeature/component 
- Randomly generated obstacle
- After character hitting
  - Reduce health
  - Reduce speed
  - Obstacle disappear 
- Interaction with character
  - character can jump over the obstacles
## **Examples** 

**obstacles & reduce health**: The obstacles can be roadblocks, aliens or disasters. For example, in the ‘Subway Surfers’ game on mobile, there will be oncoming obstacles like moving subways, poles, tunnel walls, and barriers that need to be avoided crashing into. If you crash into one obstacle, the game is over. We can change it into the hp system, assuming the initial hp of the player is 3 hp, you will lose one hp if you hit a specific obstacle.

**reduce speed & obstacle disappear**： The second example is ‘Road Rush’ on PC. The player will fall off the motorcycle when you crash into a pedestrian and the pedestrian will disappear. The player needs to get back on the bike to continue the game, which reduces the speed. We can change the pedestrians into aliens in our game based on the game story. When the player hits the alien (obstacle), it will reduce health.

# **Dependencies**
- Generate obstacles on a map relies on game terrain (#5 maybe)
- Reduce health, speed and determine if the character touches the obstacles relies on character status (#7)
- Assist with the character's ability to jump over obstacles (#6)

# **Milestones** 
- [x] Animation effect when the obstacle is touched
- [x] Obstacle disappear when the obstacle is destroyed 
- [x] Complete the function of slowing down 
- [x]  Complete the function of health loss (Character is blocked by obstacles)
- [x] Design of obstacle model (Aug. 29)
- [x] Achieve random distribution of obstacles (Aug. 30)

**Completion Deadline:** Aug. 30

# **Extras**
- [x] Try to achieve different effects when the character encounters different obstacles. One for health loss, one for speed loss.

# **Documentation**
- [Game Play of Obstacles](../wikis/Obstacles-Gameplay)
- [Design of Obstacles](../wikis/Obstacles)
- [Code Guidelines of Obstacles](Obstacles-Code)
# **Members**
- Shanshan (@lisslulay) (Shanshan Li)
- Haoke (@HKeG) (Haoke Sheng)
- Guanhao (@ShokuJO) (Guanhao Qiao)
- Yifan (@yyfyyfstudy1) (Yifan Yu)

**Comment by kprohith** [comment]
What is the status of the obstacles implementation? We need to have an idea about the size and placement of the objects in order to ensure that the main player character is properly integrated. - (Team 4)

**Comment by lisslulay** [comment]
W4 completed
- Character is blocked by obstacles (similar to slowing down)
- Characters touch obstacles to reduce health
- Obstacles destruction animation
- Obstacles disappear

W5: work to be done
- Design obstacle UI
- Randomly generate obstacles on endless maps, depending on map design

**Comment by lisslulay** [comment]
> What is the status of the obstacles implementation? We need to have an idea about the size and placement of the objects in order to ensure that the main player character is properly integrated. - (Team 4)

We have integrated the completed work into the main branch, but our obstacle UI has not been designed, so we still cannot determine the specific size of the obstacle.
Maybe you can use the current obstacles to try the function of characters jumping over obstacles. After the obstacle is designed, the height and distance parameters of characters jumping can be adjusted according to the size of the new obstacle.
When the obstacle design is completed, I will notify your team.

**Comment by lisslulay** [comment]
Our team designer has designed two types of obstacles. One of the obstacles is about the same height as the character, and the other one should be lower. The following is a schematic diagram of the design.


https://user-images.githubusercontent.com/78423568/131236789-fe57191c-4d00-4f74-ab94-3bb7a6b5da39.mp4

![e8055687-7680-4c8f-8480-dd372d29949a](https://user-images.githubusercontent.com/78423568/131236793-bae4c1f3-7e0c-4f21-a548-97cb1cc75520.gif)

@kprohith
