### ISSUE TITLE
Team 9 Task Ticket - History Score Board (Programming)

### ISSUE THREAD

**Issue by Bohan-is-in-the-zone** [UQdeco2800/2021-ext-studio-2#140]
# **Description**
**Task:** The file reading and writing
**Feature:** #100
 
In this task, We will implement the system that can save each time's score and load it to the history score board.
![image](https://user-images.githubusercontent.com/24644880/132439610-6571fbb1-f1aa-4f43-ac48-7e77499649d1.png)
 
# **Dependencies**
No dependency to pther team's work 

# **Milestones**
List of steps that need to be completed for this task.

1. Reading/writing to JSON file
  - [x] Create JSON file
  - [x] Write tests for JSON file
  - [x] Code for writing to JSON file.
  - [x] Code for reading from JSON file.

2. Code for saving the scores after game over
  - [ ] Write data in JSON format
  - [ ] Save to JSON file
  - [ ] Write tests
  - [ ] Save scores to JSON file

3. Code for displaying the scores on the board.
  - [ ] Pull data from JSON file
  - [ ] Display table in desired format (UI)
  - [ ] Write tests
  - [ ] Display scores to JSON file

 
# **Member**
@Bohan-is-in-the-zone (Bohan Xu)
@YiYang200 (Yi Yang)
@yungseop (YoungSeob Lee)
@pranavdhoolia (Pranav Dhoolia)
