### ISSUE TITLE
Team 9 Task Ticket  - History score board and Improve the clock icon and scoreboard

### ISSUE THREAD

**Issue by Bohan-is-in-the-zone** [UQdeco2800/2021-ext-studio-2#142]
# **Description**
**Task:** The file reading and writing
**Feature:** #100
 
In this task, We will design the history scoreboard and improve the clock icon and scoreboard. 

Feature 2: Design the “past scoreboard”

 
# **Dependencies**
No dependency on other team's work 

# **Milestones**
List of steps that need to be completed for this task.

Feature1: 
Improve the clock icon(GIF)
- [x] Design the gif items. (Keyu Bai) (09/05 finish)
- [ ] Coding following the “Animations wiki page” do the coding part. (Pranav Dhoolia) (09/07 finish)
- [x] User testing. (Keyu Bai) (09/11 finish)
- [x] Improve by the user testing results(or not, depends on user testing results). (Keyu Bai) (09/13 finish)

Improvement of scoreboard
- [x] Design the scoreboard looking more like a pixel art style. (YoungSeob Lee) (09/07 finish)

Design the “History scoreboard”
- [x] Design board assets decoration jewelry + 'history scores' special font. (Yi Yang) (09/08 finish)
- [x] Design the main board and 'attempts' + 'scores' font styles (YoungSeob Lee) (09/09 finish)
- [x] Merge the assets together to come up with the final history scoreboard (YoungSeob Lee) (09/10 finish)
- [ ] User testing.
- [ ] Improve by the user testing results.

- [ ] (Sep.11) Finish the design. 

# **Member**
@Bohan-is-in-the-zone (Bohan Xu)
@YiYang200 (Yi Yang)
@Noarrrr (Keyu Bai)
@yungseop (YoungSeob Lee)
@pranavdhoolia (Pranav Dhoolia)

**Comment by Bohan-is-in-the-zone** [comment]
# **Description**
**Task:** The file reading and writing
**Feature:** #100
 
In this task, We will design the history score board. 
Feature1: Improve the clock icon and scoreboard(GIF)
Design the gif items. 
Coding following the “Animations wiki page” do the coding part. 
User testing. All designers
Improve by the user testing results(or not, depends on user testing results).

Feature 2: Design the “past scoreboard”
Design the draft.  Yi Yang + YoungSeob Lee
User testing. All designers
Improve by the user testing results. Yi Yang

 
# **Dependencies**
No dependency to pther team's work 

# **Milestones**
List of steps that need to be completed for this task.
- [ ] (Sep.11) Finish the file reading and writing system. 

 
# **Member**
@Bohan-is-in-the-zone (Bohan Xu)
@YiYang200 (Yi Yang)
@Noarrrr (Keyu Bai)
@yungseop (YoungSeob Lee)
@pranavdhoolia (Pranav Dhoolia)

**Comment by Butcanudothis** [comment]
@Bohan-is-in-the-zone and @Noarrrr , to maintain consistency over the design background, we'd like collaborate on your history score board design background image. Our designer @Zibo1 has created an appealing art work and we'd like you to use it as reference.

**Comment by Butcanudothis** [comment]
![ac_bg](https://user-images.githubusercontent.com/51348806/132641368-c285397d-68b7-4bde-b75c-1bc42968f50b.png)

**Comment by Noarrrr** [comment]
> @Bohan-is-in-the-zone and @Noarrrr , to maintain consistency over the design background, we'd like collaborate on your history score board design background image. Our designer @Zibo1 has created an appealing art work and we'd like you to use it as reference.

@Butcanudothis, yes we'd like to work on this together. Please share the psd link.

**Comment by Noarrrr** [comment]
Looks great! We will refer to the design style of the background to be unified.

**Comment by Bohan-is-in-the-zone** [comment]
> Looks great! We will refer to the design style of the background to be unified.
👍 @Butcanudothis no problem :)

**Comment by Zibo1** [comment]
Here you go @Noarrrr , link to our psd. 
[https://shared-assets.adobe.com/link/6ced6ed7-eed4-46e4-5522-5711321e5a9d](https://shared-assets.adobe.com/link/6ced6ed7-eed4-46e4-5522-5711321e5a9d)
