### ISSUE TITLE
Team 4 Sprint 2: Task 7 - Design player movements and animations for item pickups.

### ISSUE THREAD

**Issue by kprohith** [UQdeco2800/2021-ext-studio-2#144]
# **Description**
**Task:** [Design player interactions while picking-up items](#144)
**Feature:** [Team 4 Feature Ticket Sprint 2 - Main Player Character Obstacle, Item and Attack Interactions and Animations](#136)

During the game, the protagonist will find various items that can be picked up and use them to bring benefits to himself. Therefore, in this task stage, we will design actions suitable for the protagonist to pick up props to improve the interactivity of the game.
 
## **Example (optional)**

- Design the connection effect of the character picking up the props, showing the interaction between the protagonist and the items.
- At this stage, we will make an initial animation based on picking up a prop. In the future, different picking actions may occur due to the change of props.

 
# **Dependencies** 
There are a few tasks that will be the dependencies of this task. 
- [x] The perspective of the game character is affected by the loop mechanism of the game map. In order to pick up the props reasonably, it needs to cooperate with the map design. (#5)
- [x] Which items can be picked up may affect the action design of the main character. (#9)
# **Tasks**
Detailed task description.
- [x] Task 3.1: Design the character's picking image according to the items and the rationality of the action.
- [x] Task 3.2: Connect images to form an atlas, and make pick-ups animations.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Task 3.1 (Sept. 11)
- [x] Task 3.2 (Sept. 12)

**Completion Deadline:** Sept. 14

 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Jiacheng Ni - @RecklessPotcover (Alex)
- Jescy Xu - @enmmjc 
- Yingxin Liu - @LIU-Evelyn

**Comment by LIU-Evelyn** [comment]
Since there is not much difference in the size of the existing items, we finally decided to use the same set of pickup actions for the time being.
![main_player_pickup_1](https://user-images.githubusercontent.com/88132643/132949670-8090ca72-0e6f-40d3-942b-19c6708b7ff8.png)
![main_player_pickup_2](https://user-images.githubusercontent.com/88132643/132949672-2c9f3fbc-0e85-4edc-ac93-3507a15f8ee3.png)
![main_player_pickup_3](https://user-images.githubusercontent.com/88132643/132949675-39a0c684-ca75-4b0b-b144-42ef778147aa.png)
![main_player_pickup_4](https://user-images.githubusercontent.com/88132643/132949678-f4ab469c-dd8d-481b-a09d-f01eadbc3e00.png)
