### ISSUE TITLE
Team 4 Sprint 2: Task 8 - Integrate player movements and animations for item pickups. (Sept. 13)

### ISSUE THREAD

**Issue by kprohith** [UQdeco2800/2021-ext-studio-2#145]
# **Description**
**Task:** [Integrate player movements and animations for item pickups](#145).
**Feature:** [Main Player Character Obstacle, Item and Attack Interactions and Animations](#136)
 
This function is dedicated to the realization of the protagonist's actions for item pickups performed in the game, integrating the protagonist’s aesthetic image with the respective change in the image when picking up items. We need to consider the interactions, movements it needs to perform when it gets near to the item, and how this interaction will affect its appearance in the game. Therefore, it is also necessary to determine the different images of the main character due to changes in their movement during the interaction process. Each image should clearly correspond to the required intervals of item pickup state.
 
- [x] Implement movement physics required for pickup movement
- [x] integrate the movement with the procedural map generation/pathway generation component when ready
- [x] Implement character item pickup movement animation

# **Dependencies**
- Design player movements and animations for item pickups. (#144)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 Integrate the item pickup animation atlas with the game (Sept. 10)
- [x] Step 2 Implement and adjust the physics of the item pickup movement. (Sept. 11)
- [x] Step 3 Implement item pickup animation. (Sept. 12)
 
**Completion Deadline:** Sept. 13
 
 
# **Documentation**
[Main Character](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Main-Character)

# **Member**
- Prateek Kumar Gupta (@prateek45) 
- Rohith Palakirti (@kprohith)

**Comment by prateek45** [comment]
I have added description to the task

**Comment by prateek45** [comment]
Task Completed
