### ISSUE TITLE
Code implementation of remote attack monster

### ISSUE THREAD

**Issue by yyfyyfstudy1** [UQdeco2800/2021-ext-studio-2#153]
# **Description**
**Task:** Code implementation of remote attack monster
**Feature:** [Active attacker](#105 )

Complete the code for the monster's remote attack. Realize that monsters that appear in the sky will throw small monsters to track and attack the player
 

# **Dependencies**
- [x] Requires animation effects of flying monsters in the sky (#108 )
- [x] Requires animation effect of the little monster sprint attack(#109  )

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Set up monster tracking logic (Sept.9)
- [x] Set the logic of disappearing after monster attack (Sept.10)
- [x] Upload related animation effects (Sept.12)
 
**Completion Deadline:** Sept.12

 
# **Documentation**
- [Obstacles Code](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Obstacles-Code)
 
# **Member**
- Name (@yyfyyfstudy1) (Yifan Yu)
