### ISSUE TITLE
Team1 task - Random achievement rewards system

### ISSUE THREAD

**Issue by johnxu7** [UQdeco2800/2021-ext-studio-2#157]
## Description
Task: Ticket Random achievement rewards
Feature: [Dropping random items when player getting achievement.](https://github.com/UQdeco2800/2021-ext-studio-2/issues/156)

Implementing rewards system during the game.

## Dependencies
No dependency to other team's work

## Milestones

List of steps that need to be completed for this task.

- [ ]  Implementing and fixing problem
- [ ]  Finish the design (Sep.11)
- [ ] Unit test (if necessary) and wiki writing (Sep. 14)

## Documentation

- [Main description of feature](url)
- [User documentation](url)
- ...

## Member

- Jiahe ZHAO(@PaddyZz)
- Liwen Jin(@LiwenJin2829)
- Yuehan Xu (@johnxu7)
- Katrina Fu (@katrinafu1)

**Comment by ThatTechedGuy** [comment]
@Yonarp @johnxu7 @PaddyZz Let me know what you need from the Achievements System.
