### ISSUE TITLE
team 5 sprint 2 feature ticket- update bag system and implement item bar

### ISSUE THREAD

**Issue by sumermakhija** [UQdeco2800/2021-ext-studio-2#159]
### Description
players can store a limited number of items in the bag system and also have it visible on the game screen 

### Subfeatures/optional

- additional storage of items 

### Dependancies
working with team 1 and 3 to store coins, other abilities and items that may cause buffs and debuffs, etc.

### Milestones

- [ ] finish the code for updated bag system
- [ ] finish design for item bar
- [ ] finish code for item bar
- [ ] store coins for team 1

### Members
-Name (GitLab Username) (Slack Handle)
-Sumer Makhija sumermakhija Sumer Makhija
