### ISSUE TITLE
Team1 Sprint 2 - Adding new items

### ISSUE THREAD

**Issue by LiwenJin2829** [UQdeco2800/2021-ext-studio-2#161]
# **Description**
We will add several new items for this sprint. In order to use the buff/debuff effect designed by team 3.
- **Medicine**: Remove the player's dizziness, poisoning, and deceleration state
- **Gold coin**: 

## Existing Items
- **Water**: Restore the thirsty value
- **Apple**: Restore the hungry value
- **First Aid Kit**: Increase the upper limit of life value
- **Bandage**: Restore the health value

## **Examples (optional)**
- **Medicine**: The player can pick up medicines in the game, and the medicines will be stored in the inventory. When the player is in a state of dizziness, poisoning, or deceleration, using this item can remove the negative state

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Design and Discussion of new items (Sep. 5)
- [ ] Implementation of new items (Sep. 12)
- [ ] User Testing (Sep. 13)
- [ ] Adding related Wiki page (Sep. 13)

**Completion Deadline:** Sep. 14

# **Documentation**
- [Sprint 2 Feature](https://github.com/UQdeco2800/2021-ext-studio-2/issues/158)
- [Sprint 1 Feature](https://github.com/UQdeco2800/2021-ext-studio-2/issues/9)
