### ISSUE TITLE
Storyline Integration with Design Team (Sept. 8)

### ISSUE THREAD

**Issue by Butcanudothis** [UQdeco2800/2021-ext-studio-2#164]
# Description 
To collaboratively work and decide on a game story. Game story chapters will be provided in the game as a reward system and will be unlocked when the user unlocks certain achievements / performs difficult feats. 

# Working Document
Team 7 and Team 9 (and more teams if they volunteer) will be working together on the following document.
https://docs.google.com/document/d/10iqa9jgNjII8JlVJWOfthIb4c4JEPMbriErVovhhtAs/edit#

# Milestones 
- [x] Write chapter 1 of the game story
- [x] Write chapter 2 of the game story
- [x] Write chapter 3 of the game story
- [x] Write chapter 4 of the game story
- [x] Write chapter 5 of the game story 
- [x] Document Game Story on the Wiki

# Extras
Game story art for chapters 1  - 5 

# Members / Editors 
- Aditya Singh Cheema @addiii4
- Keyu Bai (Nora) @Noarrrr

**Comment by Noarrrr** [comment]
Hi, I am from the Team 9 designer team and we'd like to work with the team story part @Bohan-is-in-the-zone @YiYang200 @yungseop

**Comment by Butcanudothis** [comment]
@Noarrrr yeah, it would be great to work on this. @addiii4 is working on this. Please communicate with him for the same.

**Comment by addiii4** [comment]
Team 7 and Team 9 will be working together on the following document.
[https://docs.google.com/document/d/10iqa9jgNjII8JlVJWOfthIb4c4JEPMbriErVovhhtAs/edit#](https://docs.google.com/document/d/10iqa9jgNjII8JlVJWOfthIb4c4JEPMbriErVovhhtAs/edit#)

**Comment by lisslulay** [comment]
Team8 made some comments in the file. Now the story and enemies/obstacles don't seem to match very well. We hope that in the future we can associate enemies/obstacles with the story.

**Comment by Butcanudothis** [comment]
> Team8 made some comments in the file. Now the story and enemies/obstacles don't seem to match very well. We hope that in the future we can associate enemies/obstacles with the story.

Yes sure. For now, you can ask team 8 designers to modify the design if possible in this sprint or we can fix this inconsistency in the next sprint.
I have answered some of your queries in the document as well.

**Comment by lisslulay** [comment]
> > Team8 made some comments in the file. Now the story and enemies/obstacles don't seem to match very well. We hope that in the future we can associate enemies/obstacles with the story.
> 
> Yes sure. For now, you can ask team 8 designers to modify the design if possible in this sprint or we can fix this inconsistency in the next sprint.
> I have answered some of your queries in the document as well.

Hello, I saw your comments.
For now, if this story is the mainstay, the background and elements in the game need to be changed.
Whether to change the story or change the current design, maybe everyone can vote in the next studio, which is fair to all the teams.

**Comment by lisslulay** [comment]
> > > Team8 made some comments in the file. Now the story and enemies/obstacles don't seem to match very well. We hope that in the future we can associate enemies/obstacles with the story.
> > 
> > 
> > Yes sure. For now, you can ask team 8 designers to modify the design if possible in this sprint or we can fix this inconsistency in the next sprint.
> > I have answered some of your queries in the document as well.
> 
> Hello, I saw your comments.
> For now, if this story is the mainstay, the background and elements in the game need to be changed.
> Whether to change the story or change the current design, maybe everyone can vote in the next studio, which is fair to all the teams.

Our designer has replied.

**Comment by Butcanudothis** [comment]
yeah, changing designs might not be the best idea. I have also added some comments.

**Comment by Butcanudothis** [comment]
@lisslulay , your designers have suggested adding spaceships to game background. Please contact team-6 to make necessary changes by the end of sprint 2.

**Comment by lisslulay** [comment]
> @lisslulay , your designers have suggested adding spaceships to game background. Please contact team-6 to make necessary changes by the end of sprint 2.

I understand you very well, the spaceship is one of the elements in the story that you very much want to keep. The designer in my group did all the work they should do in this sprint and gave you suggestions on how to keep this element.  I'm glad you can adopt our suggestion.

Hope that others modify their design requires very good reasons.  There is nothing unreasonable about the current team 6 background. The reason for them to modify is to satisfy your story. You can use stories to attract them and suggest changes.  As for whether to adopt the suggestion, it should be decided by team 6. I believe we have no reason to order others what to do, we only have the right to suggest.

 I don't know why the change must be made by the end of sprint2 because it really exceeds the content of the feature ticket of the team6. If you insist that they must make changes immediately, I think you can try.

**Comment by GavintheLionHeart** [comment]
I just want to confirm, could you make it detail about the pixel issue? Didn't see any inconsistency at this moment, and we are following the pixel guide made by Team4

**Comment by lisslulay** [comment]
> > I just want to confirm, could you make it detail about the pixel issue? Didn't see any inconsistency at this moment, and we are following the pixel guide made by Team4. (designer from team8)
> 
> I think the sizing might be a little off. Please confirm with @RecklessPotcover on this. It is only a minor issue. Dont worry. 😅

Hi, you have noticed a very good question. Our designer may not answer comprehensively, because they are really designed according to the characters.

This problem is not in the design but in the code (if I understand it correctly😅). In the game, the proportions of the characters are inconsistent with their original design (approximately enlarged by 2.5 times). Therefore all other pictures need to be enlarged to match the characters.

In the picture below, I cancelled the magnification of all the objects. The people and objects on this one are in their original proportions.
![image](https://user-images.githubusercontent.com/78423568/132944110-de468d7b-59be-41de-931a-551209a2d4a1.png)

**Comment by Butcanudothis** [comment]
> > @lisslulay , your designers have suggested adding spaceships to game background. Please contact team-6 to make necessary changes by the end of sprint 2.
> 
> I understand you very well, the spaceship is one of the elements in the story that you very much want to keep. The designer in my group did all the work they should do in this sprint and gave you suggestions on how to keep this element. I'm glad you can adopt our suggestion.
> 
> Hope that others modify their design requires very good reasons. There is nothing unreasonable about the current team 6 background. The reason for them to modify is to satisfy your story. You can use stories to attract them and suggest changes. As for whether to adopt the suggestion, it should be decided by team 6. I believe we have no reason to order others what to do, we only have the right to suggest.
> 
> I don't know why the change must be made by the end of sprint2 because it really exceeds the content of the feature ticket of the team6. If you insist that they must make changes immediately, I think you can try. :)

Yeah I meant can your team suggest this(it was probably lost in translation), i don't think it should take much time to add in background, that's why i thought we could do it in sprint 2 but future sprints would be fine too.

**Comment by Butcanudothis** [comment]
> I just found out that the game will forcibly compress anything of any size to the size of a grid. I will look into this issue again, thank you very much for your reminder.
> -------------------------------------------------The following is wrong-------------------------------------------------------------
> 
> Hi, you have noticed a very good question. Our designer may not answer comprehensively, because they are really designed according to the characters.
> 
> This problem is not in the design but in the code (if I understand it correctly😅). In the game, the proportions of the characters are inconsistent with their original design (approximately enlarged by 2.5 times). Therefore all other pictures need to be enlarged to match the characters.
>
I think the code involving size might be the issue here. But, I'd recommend just resizing the assets and maintaining same aspect ratio (to have square pixels).

**Comment by lisslulay** [comment]
> > I just found out that the game will forcibly compress anything of any size to the size of a grid. I will look into this issue again, thank you very much for your reminder.
> > -------------------------------------------------The following is wrong-------------------------------------------------------------
> > Hi, you have noticed a very good question. Our designer may not answer comprehensively, because they are really designed according to the characters.
> > This problem is not in the design but in the code (if I understand it correctly😅). In the game, the proportions of the characters are inconsistent with their original design (approximately enlarged by 2.5 times). Therefore all other pictures need to be enlarged to match the characters.
> 
> I think the code involving size might be the issue here. But, I'd recommend just resizing the assets and maintaining same aspect ratio (to have square pixels).

I just checked the pictures of almost all the group designs and found that their original size is shocking.

In the wiki, the screen resolution is set to 570*320px.
![image](https://user-images.githubusercontent.com/78423568/132946110-e6e23ee4-088d-4ee0-8b21-1f5070415994.png)

But in the actual design, almost no team designs according to this size.

The following picture shows the comparative size of these elements, the red block in the middle is the specified screen size.
![image](https://user-images.githubusercontent.com/78423568/132946120-549b917e-c9a1-4e96-b889-4b82948f8c44.png)

Even the design of the character itself has exceeded the size of the screen.
The following picture is the size of the character.
![image](https://user-images.githubusercontent.com/78423568/132946133-5d362f18-7aa7-482f-a546-645001ee1a11.png)

In this way, only these 3 almost invisible designs are designed with reference to the screen size in the wiki.
![image](https://user-images.githubusercontent.com/78423568/132946272-8f3825e7-727a-4e1a-9125-0edff429bead.png)

This is a big problem, we don't have a unified standard now, maybe next time in the studio, we can discuss this problem.

**Comment by Butcanudothis** [comment]
@lisslulay can we talk over discord? I think this discussion in this ticket might be off topic

**Comment by lisslulay** [comment]
> @lisslulay can we talk over discord? I think this discussion in this ticket might be off topic

There is a problem with the discord in my network. But I think I know what I am confused, it is my fault 😅
![image](https://user-images.githubusercontent.com/78423568/132947295-76f83395-b638-4c1b-8e4a-b57626a54116.png)
This is what they designed with a square grid, This is what they designed with a square grid, but the pixels of the grid are too small, resulting in blur. Our designer has decided to use bitmaps to design it.

**Comment by Butcanudothis** [comment]
@lisslulay can you do zoom? Room 944 446 6812

**Comment by Butcanudothis** [comment]
Update: deleted off topic comments about pixel sizing for future sprints.
