### ISSUE TITLE
Team1 Sprint2 - Task ticket - Applying the gold coins system

### ISSUE THREAD

**Issue by katrinafu1** [UQdeco2800/2021-ext-studio-2#167]
# **Description**
**Task:**Applying the gold coins system for the props store (#3).
**Feature:** Props Store(#158 )
 
The gold coins system will be including the gold coins shows on the map, the total coins the player have collected in the game(Showing this in the props store) and showing gold coins the player has collected per game. 
 
## **Example (optional)**
- **Gold coins collected per game**: The gold coins collected in the game will be shown on the top of the screen
- **Total gold coins collected throughout the history**: The system will save the total gold coins the player has collected in the previous rounds, so they can use the coins to buy props in the prop store.
 
# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.
 
- [ ] Dependency 1 (#xx)
- [ ] Dependency 2 (#xx)
 
e.g.
- [ ] Texture needs to be created for armour laying on map.
- [ ] Texture needs to be created for player wearing armour.
- [ ] Textures need to be created for partially, and then fully, broken armour.
- [ ] Mechanism needs to be implemented for armour to be placed onto map.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Finish the gold coins design(Aug. 19)
- [ ] Add randomly appeared gold coins on the map (Aug. 20)
- [ ] Show the gold coins number the player have collected (Aug. 23)
- [ ] Step 4 (Aug. 23)
 
**Completion Deadline:** Aug. 23
 

# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitLab Username) (Slack Handle)
- Richard (@AppleByter) (Richard Thomas)
