### ISSUE TITLE
Team 4 Task Ticket 2 - Designing Movements of Character

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2021-ext-studio-2#17]
# **Description**
**Task:** [Designing Basic Movements of Character](#17)
**Feature:** [Team 4 Feature Ticket - Main Player Character](#6)

Design a feasible movement interactive image of the protagonist based on the basic image
 
## **Example (optional)**

- According to the Team 4 Task Ticket 1 (#26), design the basic images of the characters - Images referring to the frames required for movement animation. 
- The animations refer to what it should be looked like when the character moves to the left or the right or avoid obstacles; and also when it's standing being idle, and when it hit the obstacles.

 
# **Dependencies** 
There are a few tasks that will be the dependencies of this task. 
- [x] The perspective of the game determines the image of the characters when facing different directions, e.g. when the game performs scroll view, the characters can face left or right. (#5)
- [x] This will affect how the character looks when idling in the game - referring to posture. (#18)
 
# **Tasks**
Detailed task description.
- [x] Task 2.1: What will the character look like when it's just standing, in idle status.
- [x] Task 2.2: What will the character look like when it moves around, e.g. moving left/right or dodging an obstacle (at least one action need to be done).
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Task 2.1 (Aug. 21)
- [x] Task 2.2 (Aug. 29)

**Completion Deadline:** Aug. 31

 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Jiacheng Ni - @RecklessPotcover (Alex)
- Jescy Xu - @enmmjc 
- Yingxin Liu - @LIU-Evelyn

**Comment by LIU-Evelyn** [comment]
The right view and left view of the character: 
![right view](https://user-images.githubusercontent.com/88132643/130445607-b1f3651d-34a4-4bea-a072-30243d7a228e.png)
![left view](https://user-images.githubusercontent.com/88132643/130445646-162f8733-fa2a-4c5f-a863-a21814e575ab.png)

**Comment by RecklessPotcover** [comment]
The front view of our character.
![front-view](https://user-images.githubusercontent.com/31987631/130456449-f06ad04d-a9bd-4e92-8a30-b302d0ef24f5.png)

**Comment by RecklessPotcover** [comment]
Updated a stroke outlined front view of the main character for better clarity.
![mpc_front_stroke](https://user-images.githubusercontent.com/31987631/130561863-c97e77c0-fe77-439b-856a-68e8ae331a3e.png)

**Comment by LIU-Evelyn** [comment]
stroke the image:
![mpc-bothview-sprint1](https://user-images.githubusercontent.com/88132643/130637198-904d774b-56cd-49a5-b666-7180a6dfb1e4.png)

**Comment by LIU-Evelyn** [comment]
changed the main player  and unified the character size and style with members of other teams. (try to do animation)

**Comment by LIU-Evelyn** [comment]
changed the main player  and unified the character size and style with members of other teams. (try to do animation) - not the final frames
![main_player_bothsides](https://user-images.githubusercontent.com/88132643/131255884-4f872469-cc57-46be-be38-3e9ed35f7a9c.png)

**Comment by RecklessPotcover** [comment]
Created these frames for the movement animation of our character. @LIU-Evelyn and I will integrate these frames into an atlas file for our coders to complete animation implementation.
![main_player_move_2](https://user-images.githubusercontent.com/31987631/131259990-76745e33-bedf-4373-a396-1d8cb92e96bb.png)
![main_player_move_3](https://user-images.githubusercontent.com/31987631/131259989-7ac32465-99ba-4525-9d51-c76dd0db8974.png)
![main_player_move_4](https://user-images.githubusercontent.com/31987631/131259987-6eb29454-79b1-4568-ad2b-ed027f0d473c.png)
