### ISSUE TITLE
Obstacles/Enemies User test & design wiki

### ISSUE THREAD

**Issue by lisslulay** [UQdeco2800/2021-ext-studio-2#173]
# **Description**
**Task:** User test (#173 )
**Feature:** Active attacker (#105 )
 
# **Milestones**
- [x] user test for enemies
- [x] user test for meteorites
- [x] design wiki for two enemies
- [x] design wiki for meteorites
 
**Completion Deadline:** Sep.13
 
# **Documentation**
- [User test of obstacles](../wikis/Obstacle-testing)
- [Design of obstacles](../wikis/Obstacles)
- need to create extra wiki for enemies
 
# **Member**
- Haoke (@HKeG) (Haoke Sheng)
- Guanhao (@ShokuJO) (Guanhao Qiao)
- He Zhu (@GavintheLionHeart) (He Zhu)
