### ISSUE TITLE
Obstacles/Enemies Code test & Code guideline (Wiki)

### ISSUE THREAD

**Issue by lisslulay** [UQdeco2800/2021-ext-studio-2#174]
# **Description**
**Task:** Code test & Code guideline (Wiki) (#174 )
**Feature:** Active attacker (#105 )
 
# **Milestones**
- [x] Code test for enemies
- [x] Code test for meteorites
- [x] Code guideline for two enemies
- [x] Code guideline for meteorites
 
**Completion Deadline:** Sep.13
 
# **Documentation**
- [Game play of obstacles](../wikis/Obstacles-Gameplay)
- [Code guidelines of obstacles](../wikis/Obstacles-Code)
- need to create extra wiki for enemies
 
# **Member**
- Shanshan (@lisslulay) (Shanshan Li)
- Yifan (@yyfyyfstudy1) (Yifan Yu)
