### ISSUE TITLE
Coding the Achievements Screen GUI (Sept. 10)

### ISSUE THREAD

**Issue by ThatTechedGuy** [UQdeco2800/2021-ext-studio-2#177]
**Original Feature**: #127 

# Description 
The idea is to score the record of achievements for each game in local storage, add a brand new achievements screen which shows locked and unlocked achievements (i.e, achievements which have already been encountered during the game). 

# Example
**Displaying unlocked achievements**: If Veteran Gold, Bronze and Silver are unlocked, only the most prestigious achievement, i.e, Gold will be displayed in the Achievement Records. If Gold was not unlocked, Silver will be displayed and the image of the Veteran Gold achievement will be dimmed (in order to visually deem it unlockable). 

# Milestones
- [ ] Coding the unlockable chapters GUI (Sept. 10)
- [ ] Coding locked achievements (Sept. 10)
- [ ] Coding unlocked achievements (Sept. 10)

# Members 
- Vishal Gupta @ThatTechedGuy 
- Akshay Varma @Butcanudothis
