### ISSUE TITLE
Coding unlockable storyline chapters (Sept. 10)

### ISSUE THREAD

**Issue by ThatTechedGuy** [UQdeco2800/2021-ext-studio-2#178]
**Original Feature**: #127 

# Description 
Chapters can be unlocked on certain gold achievements. These will be displayed in the Achievements Screen. 

# Milestones 
- [ ] Coding the Achievements Screen GUI for unlockable chapters (Sept. 10)@Butcanudothis @ThatTechedGuy 
- [ ] Coding the logic for unlocking a chapter (Sept. 10) @ThatTechedGuy 
- [ ] Testing the logic for unlocking a chapter (Sept. 10) @ThatTechedGuy

# Members 
- Vishal Gupta @ThatTechedGuy 
- Akshay Varma @Butcanudothis
