### ISSUE TITLE
Team 6-  task ticket 1- Design the game environment

### ISSUE THREAD

**Issue by katrinafu1** [UQdeco2800/2021-ext-studio-2#18]
# **Description**
**Task:** Design the game environment.
**Feature:** Infinite loop game environment (#5 )
 
Design the UI of the game background and terrain which can be connected infinitely throughout the whole game. Confirm the camera angles and the perspective of the player.
 
 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design and set the game background(Aug. 19)
- [x] Sketch out the terrain of the game environment(Aug. 20)
- [x] Confirm the player perspective and the camera angle(Aug. 20)
- [x] Design the whole game environment(Aug. 21)
- [x] Confirm on the final design and merge the background(Aug. 23)
 

 
# **Documentation**
- [Camera angle and player perspective](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Camera-angle-and-the-player's-perspective)
- [Background's style](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Style)
- ...
 
# **Member**
- Name (GitLab Username) (Slack Handle)
- Yuqi Yang (Marco777777) (Yuqi Yang)
- Yinghao Fu (katrinafu1) (Katrina Fu

**Comment by lisslulay** [comment]
Hi, 
Are you sure what the background of the game looks like?
What is the perspective of the game?
The game has only one road or multiple roads?
The design of group 8 requires you to provide this information.
Thanks.

**Comment by katrinafu1** [comment]
> Hi,
> Are you sure what the background of the game looks like?
> What is the perspective of the game?
> Does the game have only one road or multiple roads?
> The design of group 8 requires you to provide this information.
> Thanks.

The perspective will be a 2D third perspective horizontally face to the character, similar to the Mario game. We have already designed the background but haven't sketched out the terrain yet. We'll inform you guys once we have finished.

**Comment by lisslulay** [comment]
> > Hi,
> > Are you sure what the background of the game looks like?
> > What is the perspective of the game?
> > Does the game have only one road or multiple roads?
> > The design of group 8 requires you to provide this information.
> > Thanks.
> 
> The perspective will be a 2D third perspective horizontally face to the character, similar to the Mario game. We have already designed the background but haven't sketched out the terrain yet. We'll inform you guys once we have finished.

Is it something like this?
![image](https://user-images.githubusercontent.com/78423568/130197280-32709a0d-4305-40e0-87a4-735bee1efe60.png)

**Comment by lisslulay** [comment]
I added this wiki page to the sidebar in the wiki column so that more people can find it easily 😄

**Comment by katrinafu1** [comment]
![Game Bg](https://user-images.githubusercontent.com/88012376/131208461-4cc97558-e5c7-4234-8d76-de6adc0ccd27.png)
Game background's size 1140 × 640, it would be 9*9 pixels per squares
