### ISSUE TITLE
Team1 Sprint2- task ticket- props store design and implementation

### ISSUE THREAD

**Issue by katrinafu1** [UQdeco2800/2021-ext-studio-2#202]
# **Description**
**Task:**  Props store ui design and implementation
**Feature:** [props store](#158 )
 
The props store allows the player to buy the props by using the gold coins collected in the game. Players can buy multiple props at the same time, and each prop is allowed to use once only. 
 
## **Example (optional)**
- **Protection shield**: After the player has bought the protection shield, the obstacles will not harm the character if the player accidentally touches them. Once the player has touched the obstacles, the protection will be gone.
- **More HP**: The player will have more HP in the next game.
-  **Food**: The player will have more food in the next game.
-  **Water**: The player will have more water in the next game.

# **Dependencies**

- [ ] Food and water system(#36 )
- [ ] Health system (#35 )
- [ ] Character protection shield (#136)
 
e.g.
- [ ] Texture needs to be created for armour laying on map.
- [ ] Texture needs to be created for player wearing armour.
- [ ] Textures need to be created for partially, and then fully, broken armour.
- [ ] Mechanism needs to be implemented for armour to be placed onto map.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Discussion about what kind of props should be included(Sep. 8)
- [ ] Finalise the props store UI design (Sep. 9)
- [ ] Implement the gold coin system (Sep. 10)
- [ ] Implement the props store UI coding (Sep. 11)
- [ ] Implement the props applied in the game (Sep. 13)
 
**Completion Deadline:** Sep.13
 
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitLab Username) (Slack Handle)
- Yinghao Fu (@katrinafu1) (Katrina Fu)
