### ISSUE TITLE
Score Calculator UI

### ISSUE THREAD

**Issue by Bohan-is-in-the-zone** [UQdeco2800/2021-ext-studio-2#21]
# **Description**
**Task:** The interface of the timer or the score
**Feature:** Scoring System #3 
 
In this task, we will implement the interface for displaying the time. 
 
## **Example (optional)**
-: When the player has played for 67 seconds. The timer(scoreboard throughout the game) will display 1min 7sec. But in the final score, it counts 67 points. "TIME IN SECONDS = SCORES" (Only in the first sprint)
-: The board locates at the top right corner
 
# **Dependencies**
Start of the game. This is handled by the given code. 
End of the game. #7 or #5 whoever writes the game over code. 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Finds an example of a scoreboard. (Finish before 2021.08.21)
- [x] Design some simple prototypes.(Canvas Size: 600px * 600px) (Finish before 2021.08.24)
- [x] Make a google form investigation, to collect others opinions. (Finish before 2021.08.25)
- [x] According to the result, design which one we are going to use. (Finish before 2021.08.27)
- [x] Design the final one for the game. (Finish before 2021.09.01)

**Completion Deadline:** Aug. 26

 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
@Bohan-is-in-the-zone (Bohan Xu)
@YiYang200 (Yi Yang)
@Noarrrr (Keyu Bai)
@yungseop (YoungSeob Lee)
@pranavdhoolia (Pranav Dhoolia)
