### ISSUE TITLE
Achievement Enhancement User Testing

### ISSUE THREAD

**Issue by addiii4** [UQdeco2800/2021-ext-studio-2#218]
# **Description**
**Feature:** [Major Achievements System Enhancement](#126)
 
This questionnaire is based on the features added in sprint 2 to enhance the achievement system from sprint 1. Users were made to play the game via remote control on zoom. First they tested the game from sprint 1 and then they tested the game from sprint 2.
 
# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.
 
- [x] Integrate achievement notification sound (#132)
- [x] Integrating achievements bonus score functionality with the scoring system (#133)
- [x] Adding new achievements (Sept. 8) (#135)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Planning user testing methods 
- [x] Surveying
- [x] Data analysis from the survey
 
**Completion Deadline:** Sept. 13
 
 
# **Documentation**
- [Achievement Enhancement User Testing](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Achievement-Enhancement-User-Testing)
 
# **Member**
- Aditya Singh Cheema (@addiii4)
