### ISSUE TITLE
Obstacle physical attributes

### ISSUE THREAD

**Issue by lisslulay** [UQdeco2800/2021-ext-studio-2#22]
# **Description**
**Task:** [Obstacle physical attributes](#22).
**Feature:** [Random obstacles](#14)

Set the physical attributes, location, size of obstacles and display the obstacle on the map. 
Provide help for the design of the character jumping over obstacles.

# **Dependencies**
- [x] Style of obstacles need to be designed.(#27)
- [x] Where obstacles can be generated related to game map (#5)
- [x] Provide assistance to the character's ability to jump over obstacles (#6)
 
# **Milestones**
- [x] Show obstacles on the map (Aug. 20)
- [x] Adjust the position and size of obstacles (Aug. 23) 
- [x] Handle the interaction of characters jumping over obstacles (Aug. 28)
- [x] Complete the test and wiki of the above functions (Aug. 30)
 
**Completion Deadline:** Aug. 30
 
# **Documentation**
- [Game Play of Obstacles](../wikis/Obstacles-Gameplay)
- [Design of Obstacles](../wikis/Obstacles)
- [Code Guidelines of Obstacles](Obstacles-Code)
 
# **Member**
- Shanshan(@lisslulay) (Shanshan Li)

**Comment by kprohith** [comment]
Are you implementing the pathway(s) for the player to move on? Where are the obstacles going to be present?

**Comment by lisslulay** [comment]
> Are you implementing the pathway(s) for the player to move on? Where are the obstacles going to be present?

Where are the obstacles going to be present?
https://github.com/UQdeco2800/2021-ext-studio-2/issues/18#issuecomment-902496469
Like a map designed by team6, the map should have only one road, and we will put obstacles on the road.

Are you implementing the pathway(s) for the player to move on?
I don't think we will implement this. We guess that when the height is designed for the obstacles, as long as the character jumps over this height, it will avoid the obstacles, which does not require an additional pathway.
