### ISSUE TITLE
Team9 Sprint 4 Fix some small errors of Distance Value (Sprint 3 Feature Ticket --- Scoring Service Improve)

### ISSUE THREAD

**Issue by Bohan-is-in-the-zone** [UQdeco2800/2021-ext-studio-2#227]
# **Description**
_**Sprint 4: Team 9 will fix two small bugs of the distance values: the initial value and the value after returning from the new map**_

In this sprint, we will replace every lines of code using our old scoring system (`ScoringSystemV1.java`) by `ScoreService.java
` #188 In this case, our scoring system will be easier to understand and more easily to access. 

We will also add another display feature to the main game. The right bottom corner is empty. We decide to display the player's running distance from the starting point. And distance will be another parameter to calculate scores. 
 
## SubFeature/component (optional)
1. Replace old codes with new ScoreService
2. Add distance to the ScoreService
3. Display the distance in the main screen. 
4. Write tests for Sprint 2 history score display feature and ScoreService class. 
_**5. Fix two bugs**_

# **Dependencies**
Team 7 Achivement scores updating #137 
Team 5 Inventory System Score

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Add distance as another parameter of scores.          Before 15th Sep: Week 9 Studio
- [x] Design the UI board for distance.                              Before 20th Sep
- [x] Implementing code to display the distance              Before 25th Sep
- [x] Write enough tests                                                    Before sprint is due
- [ ] Fix the initial distance value to zero.                          Before 10th October
- [ ] Fix the value after returning from the new map.       Before 19th October 

**Completion Deadline:** (Date)
19th October
 
# **Members**
(Git hub name)(Slack name)
- @Bohan-is-in-the-zone (Bohan Xu)
- @YiYang200 (Yi Yang)
- @Noarrrr (Keyu Bai)
- @yungseop (YoungSeob Lee)
- @pranavdhoolia (Pranav Dhoolia)
