### ISSUE TITLE
Team 9 Sprint 3 Feature Ticket ---- Game Soundtrack Design and code implementation

### ISSUE THREAD

**Issue by Bohan-is-in-the-zone** [UQdeco2800/2021-ext-studio-2#228]
# **Description**
🎶🎼🎵 is important for a game. Team 9 will be responsible for all of the music designs of the game. 
The music designs including: main game soundtracks for different maps; short sound effects of the player's actions; soundtracks for different screens. 

The music style will be [8 bit music style or Chiptune](https://en.wikipedia.org/wiki/Chiptune). 
 
## SubFeature/component (optional)
1. Main Game soundtracks x2: one is the regular game, one is for another new scene. 
2. Sound effects for player's action (keep updating): 
    1)  Inventory System sound effects
    2)  Obstacles sound effects requested by team 8
    3) Player's jumps, attack
3. Music for different screens: main menu screen, history score screen, achivement score screen, game over screen. 

# **Dependencies**
Team 5 Inventory System #240 
Team 7 Achivements System
Designed by themselves. 
More
... according to other teams requests from discord music channel 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Main game sound tracks         Before 15th Sep: Week 9 Studio
- [x] Obstacles' sounds effects        Before 20th Sep
- [x] Player's actions sound effects Before 20th Sep
- [x] Do user tests                           Before 25th Sep
 
**Completion Deadline:** (Date)
1 October
 
# **Members**
(Git hub name)(Slack name)
- @Bohan-is-in-the-zone (Bohan Xu)
- @YiYang200 (Yi Yang)
- @Noarrrr (Keyu Bai)
- @yungseop (YoungSeob Lee)
- @pranavdhoolia (Pranav Dhoolia)

**Comment by Bohan-is-in-the-zone** [comment]
We will also create several task tickets for each feature's sound effects.
