### ISSUE TITLE
Team 6- task ticket 3- Game over screen

### ISSUE THREAD

**Issue by katrinafu1** [UQdeco2800/2021-ext-studio-2#23]
# **Description**
**Task:** Design the game over screen 
**Feature:** Infinite loop game environment(#5 )
 
Designing on the game over screen which includes the 5-second countdown prompt box and the final score.
 
## **Example (optional)**
- **Prompt box benefits**:  Players can choose whether to continue the game or end the game. The prompt box and countdown are designed in this way, and the choice is up to the player, which can improve the player's ability.
[](https://im.ge/i/445pY)
[](https://im.ge/i/44xvr)
 
# **Dependencies**

- [x] Team2 player status: The game loop will end depending on the health bar when the player is running out of life. 
 (#7 )
- [x] Team9 scoring system: Display the final score on the game over screen (#3 )

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design the UI layout of the game over screen (Aug. 19)
- [x] Implement the prompt box of play again(Aug. 20)
- [x] Cooperate with the scoring system (#3 ) to display the final score on the game over screen(Aug. 23)
- [x] Combine with player status and connect the game over status(Aug. 23)
 
**Completion Deadline:** Aug. 23
 
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitLab Username) (Slack Handle)
- Richard (@AppleByter) (Richard Thomas)

**Comment by Bohan-is-in-the-zone** [comment]
Cooperate with the scoring system (Team 9 Feature Ticket - Scoring System #3 ) to display the final score on the game over screen(Aug. 23)

To get the final score. 
Use `long finalScore = ScoringSystem.calculateFinalScore()`. The return type is a "long" because time variable often uses long 👍
Good luck
