### ISSUE TITLE
Achievement Integrations with other features

### ISSUE THREAD

**Issue by ThatTechedGuy** [UQdeco2800/2021-ext-studio-2#236]
# **Description**
Integration of the Achievements System with other parts of the game. This involves collaborations with other feature teams. Based on unlocked achievements, players will be able to unlock prop shop items, earn coins etc for the prop shop. There will be a major design overhaul of assets to make the achievements look more pleasing to the eye. An achievements history will be added for each score in the History Scoreboard. Through unlocked achievements, players will also be able to redeem attires for the main character. Bonus items will be spawned as well, when an achievement is unlocked mid game. 
 
## SubFeatures
- **History Scoreboard Achievements**: On clicking on a particular score row in the score history screen, a dialog opens which displays the list of achievements unlocked in that particular game. 
- **Asset redesign**: Major rewamp of assets for cosmetic appeal, and will follow the pixel design guidelines from the wiki in order to be more consistent with the rest of the designs within the game. 
- **Coin system / Props Shop Integration**: Achievements unlocked mid game will give the player bonus coins.
- **Bonus items integration**: Unlocking achievements will spawn a bonus item. Refining the current implementation. 
- **New achievements**: Coin amount related achievements, Distance related achievements, New items related achievements etc (TBD) 
- **Main Character Attire Integration**: Unlocked achievements can unlock attires. Make sure the concerned achievements align with the main character's attire design and vice versa. 

# **Dependencies**
- Team 1: Props Store & Coin system #231 
- Team 4: Attire System #229 
- Team 9: Current distance covered value, History scoreboard, Latest scoring system `Service Locator` API #227
- Team 1: Bonus Item UI Components #231 
- Team 1: Item UI Components to track item pickups #231 
  
# **Milestones**
- [ ] Migrating to the new scoring system `ServiceLocator` API (Sept 17)
- [ ] Bonus item integration (Sept 19)
- [ ] Designing scoreboard integration related assets (Sept 21)
- [ ] Displaying unlocked achievements in History Scoreboard (Sept 23)
- [ ] Prop store / Coin system integration (Sept 24)
- [ ] Redesigning  (Sept 21)
- [ ] Assets for new achievements (Sept 23)
- [ ] Coding new achievements (Sept 24)
- [ ] Providing unlocked achievements data for Attire System (Sept 23)
- [ ] Unit Testing persisted unlocked achievements (Sept 25)
- [ ] Unit Testing new achievements (Sept 25)
 
**Completion Deadline:** Sept. 26

# **Documentation**
- TBD
 
# **Members**
- Vishal Gupta (@ThatTechedGuy)
- Akshay Varma (@Butcanudothis)
- Zibo Gong (@Zibo1)
- Kai Wang (@Kaiwang4)
- Aditya Singh Cheema (@addiii4)

**Comment by ThatTechedGuy** [comment]
cc: @Yonarp @katrinafu1 (Team 1), @Bohan-is-in-the-zone @pranavdhoolia (Team 9), @kprohith @enmmjc (Team 4)

Please refer to the above feature ticket. We will be working closely with you this sprint (or getting tasks which indirectly concern you reviewed).

**Comment by uqtnieva** [comment]
Heads up - Team 1 has decided to focus on Item Drops rather than prop store due to member changes.

**Comment by ThatTechedGuy** [comment]
Thanks for the heads up. We will contact them and see what we can do. @uqtnieva 

cc: @Yonarp

**Comment by Butcanudothis** [comment]
Update: team 1 is working on prop store and item drops as mentioned in #231 #245.
cc: @uqtnieva

**Comment by Butcanudothis** [comment]
In Sprint 3, #283 was incomplete due to team 1 not able to implement said feature.
Completing incomplete task #283 in sprint 4. 
cc: @uqtnieva
