### ISSUE TITLE
Team 5 sprint 3 Task ticket - Item bar

### ISSUE THREAD

**Issue by yu-ang-zhang** [UQdeco2800/2021-ext-studio-2#238]
# **Description**
players can store three things in the item bar with a limited number (capacity), also have it visible on the game screen.

# **Milestones**
- [x] #281
- [x] finish the back-end coding (9. 20)
- [x] finish the front-end design (9. 27)
- [x] finish item bar (10. 3)

**Completion Deadline:** 10. 5

## **Examples (optional)**
player can see the number of items in item bar
player can use the item if the number is greater than 0

# **Dependencies**

# **Documentation**

# **Members**
- Yuang Zhang (yu-ang-zhang)
- YE Lingfeng (@TerrestrisYE) Lingfeng YE
- @Noarrrr (Keyu Bai)
