### ISSUE TITLE
Team 5 sprint 3 feature ticket - Recycle system

### ISSUE THREAD

**Issue by yu-ang-zhang** [UQdeco2800/2021-ext-studio-2#239]
# **Description**
This system can be regarded as an additional reward system. When a player collects (collides) three identical items in a row, he will receive an additional reward. 
 
 
## **Examples (optional)**
- **Part/Feature**: if the player collects three blood packs in a row, he will gets a brand-new blood pack and stores it in the 'rubbish bin'. He can use this blood pack at any time. Only one item can be stored in the rubbish bin. This means that players cannot get new rewards until the blood pack of the current reward is used

 
# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] #281 
- [x] Recycle system code
- [x] Recycle system code user testing
 
# **Design Part**
- [x] Design the draft. (due before 09.24)
- [x] Design user testing. (due before 09.30)
- [x] Improve by the user testing results(or not, depends on user testing results). (due before 10.03)

 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [User documentation](../../wikis/Game-Guide#section1)
- ...
 
# **Members**
- Name (GitLab Username) (Slack Handle) -- only one is needed if they are the same.
- YuanyeZhang(YuanyeZhang)
- YE Lingfeng (@TerrestrisYE) Lingfeng YE
- @Noarrrr (Keyu Bai)
- Yuang Zhang (yu-ang-zhang) (yuang)

**Comment by uqtnieva** [comment]
Please specify the goals. You can also update this ticket with the graphics once you have the initial sketches.
