### ISSUE TITLE
Team 6- task ticket2 - Setting up the infinite loop environment 

### ISSUE THREAD

**Issue by EvansH1997** [UQdeco2800/2021-ext-studio-2#24]
# **Description**
**Task:** Randomly generate terrain, finish the infinite loop environment and combine it with other game features
**Feature:** Infinite loop game environment(#5 )
 
Design and implement an infinite loop environment for the game based on the player's HP value. The game allows the user to continue playing the game until their HP is less than or equal to zero when the user will end the game. Randomly generate the terrain and keep the frame constantly moving to the right.
 
 
# **Dependencies**

 
- [x] Player status(Team 2): We need to collect the player's status to determine if the player has finished the game(When the player's HP is less than or equal to zero, the player ends the game. Otherwise, the player will continue playing)
- [x] Terrain's and game bf design
 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Communicate with team 2 about the player's status logic and the health bar's rules(Aug. 19)
- [x] Generate the terrain continuously(Aug. 23)
- [x] Keep the screen constantly moving to the right (Aug. 25)
- [x] Design the infinite loop environment according to the player's status (Aug. 27)
- [x] Discuss with [Team 4](https://github.com/UQdeco2800/2021-ext-studio-2/issues/33) about the player's movement to fulfill the infinite loop mode (Aug. 28)
- [x] Unit Testing and improve the code (Aug. 30)
 
**Completion Deadline:** Aug. 31
 
 
# **Documentation**
- [Camera angle and player perspective](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Camera-angle-and-the-player's-perspective)
- [Background's style](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Style)
- ...
 
# **Member**
- Name (GitLab Username) (Slack Handle)
- Richard (@AppleByter) (Richard Thomas)
