### ISSUE TITLE
Team 5 Sprint 3 Task Ticket - Inventory sound effect

### ISSUE THREAD

**Issue by TerrestrisYE** [UQdeco2800/2021-ext-studio-2#240]
# **Description**
**Task:** [Inventory sound effect](#3)
**Feature:** [Game Soundtrack Design](https://github.com/UQdeco2800/2021-ext-studio-2/issues/8)
 
Creat sound effects assets for the inventory system.

# **Dependencies**
 
- [x] Dependency 1: [Team 9 Game Soundtrack Design](https://github.com/UQdeco2800/2021-ext-studio-2/issues/228)
 
# **Milestones**
List of sound effects that needs to be completed for this task.
- [x] item select 
- [x] select switch 
- [x] use item 
- [x]  move item
- [x] drop item

# **Design Process**
- [x] Design the draft.  
- [x] User testing.(Following the team9) 
- [x] Improve by the user testing results.(or not, depends on user testing results).

**Completion Deadline:** 
 
# **Documentation**
- None
 
# **Member**
- YE Lingfeng (@TerrestrisYE) Lingfeng YE
- @Noarrrr (Keyu Bai)
