### ISSUE TITLE
Spaceship Boss

### ISSUE THREAD

**Issue by lisslulay** [UQdeco2800/2021-ext-studio-2#242]
# **Description** 
When the game progresses to a certain stage, the game will generate a boss. The character will stop running and move in a fixed range to avoid boss attacks. After successfully surviving for 10 seconds, the boss will leave and the character can move on.

## SubFeature/component 
- After the character meets the boss
  - Stop the character and move to the leftmost side of the screen
  - Jump up and down: avoid boss attacks
- Boss Spaceship
  - Small missile, from the spaceship to the left (several attacks)
  - The attack time is fixed (e.g. 10s)
  - Disappear or fly away after the attack is over  
  
![image](https://user-images.githubusercontent.com/78423568/133625906-255e9cae-37cd-4104-8045-977cb5ead5db.png)

## **Examples** 
**Boss**: To increase the difficulty and gameplay, we add a boss which can pause time. There many games have boss battles, like Super Mario, Contra, Castlevania etc. We can learn from Super Mario and change the terrain during the boss battle. And the game difficulty of Super Mario allows players to get better at it, and its style of attacks allow us to better refine the code. Another example is the Castlevania, we can use its design style as a reference which fits in the background of our game.

# **Dependencies**
- The design of the spacecraft needs to be consistent with the background story (#xx team 7)

# **Milestones** 
**Design**
- [ ] Spaceship design (general animation) Zhuhe
- [ ] Little Missile (general animation) Haoke
- [ ] Design wiki
- [ ] User test

**Code**
- [ ] code implementation: Spaceship and character shots and positions
- [ ] Code Implementation: Spaceship Attack
- [ ] code implementation: the spaceship disappeared
- [ ] code wiki
- [ ] code test

**Completion Deadline:** Oct. 4

## Extra
- [ ] Spaceship Design (Disappearing Animation) Zhuhe
- [ ] Missile disappears (animation) Haoke

# **Documentation**
- [Game Play of Obstacles](../wikis/Obstacles-Gameplay)
- [Design of Obstacles Enemies](../wikis/Obstacles-Enemies)
- [Code Guidelines of Spaceship Boss ](../wikis/Spaceship-Boss-Code)
- [User Test of Spaceship Boss](../wikis/Spaceship-Boss-Testing)

# **Members**
- Shanshan (@lisslulay) (Shanshan Li)
- Haoke (@HKeG) (Haoke Sheng)
- Guanhao (@ShokuJO) (Guanhao Qiao)
- Yifan (@yyfyyfstudy1) (Yifan Yu)
- He Zhu (@GavintheLionHeart) (He Zhu)
