### ISSUE TITLE
Monster Manual Code Implementation

### ISSUE THREAD

**Issue by yyfyyfstudy1** [UQdeco2800/2021-ext-studio-2#244]
# **Description**
Implement the code for Monster Manual. Set the background, button, table, etc. Realize the function of clicking to view the details of the monster.
 
# **Dependencies**
 - Monster Illustrated Book Design Outline (#237 ) 
 
# **Milestones**
- [x] A new screen is generated and can be entered from the main menu
- [x] Set up components
- [x] Complete the click to view details function 

 
**Completion Deadline:** Oct. 3
 
# **Extras (optional)**
- [x] Realize the function of unlocking the illustrated book

 
# **Documentation**
- [Code guidelines of Monster Manual](../wikis/Monster-Manual-Code)
 
# **Members**
- Yifan (@yyfyyfstudy1) (Yifan Yu)
