### ISSUE TITLE
Team 4 Sprint 3: Task 1 - Design the New Attires

### ISSUE THREAD

**Issue by enmmjc** [UQdeco2800/2021-ext-studio-2#247]
# **Description**
**Task:** [Design the New Attires](#)
**Feature:** [Team 4 Feature Ticket - Main Player Character](#6)

During the game, the protagonist will encounter various obstacles, and we will design suitable actions for the protagonist to avoid the obstacles. Therefore, the action image of the protagonist crouching will be realized in this task.
 
## **Example (optional)**

- Design the cohesive effect of the standing and squatting movements of the character, showing how the protagonist avoids obstacles by squatting down.
- At this stage, we will make an initial squat animation based on the lowest squat space to facilitate future improvements.

 
# **Dependencies** 
There are a few tasks that will be the dependencies of this task. 
- [ ] The perspective of the game character is affected by the loop mechanism of the game map, and it will only show an animated image that jumps to the right. (#5)
- [ ] The size of the space under the obstacle will affect the design of the character crouching. (#14)
 
# **Tasks**
Detailed task description.
- [ ] Task 3.1: Design the character's crouching image according to the available crouching space left by obstacles for the protagonist of the game.
- [ ] Task 3.2: Connect images to form an atlas, and make crouching animations (Refer to the height of the space below the obstacle in the air to ensure that the effect is unified).
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Task 3.1 (Sept. 9)
- [x] Task 3.2 (Sept. 10)

**Completion Deadline:** Sept. 14

 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Jiacheng Ni - @RecklessPotcover (Alex)
- Jescy Xu - @enmmjc 
- Yingxin Liu - @LIU-Evelyn

**Comment by RecklessPotcover** [comment]
**_Complete idle and walk sprites for a new attire comes with bronze achievement._**

**_Idle:_**

![mpc_idle_bronze](https://user-images.githubusercontent.com/31987631/135307626-8952edc7-940d-4cb5-a6e5-61f3162d39b5.png)

**_Walk:_**

![mpc_walk_bronze_1](https://user-images.githubusercontent.com/31987631/135307695-80c8219c-10ca-497b-862d-3a9b1f5aaece.png)
![mpc_walk_bronze_2](https://user-images.githubusercontent.com/31987631/135307703-41a536a5-a49f-4502-948d-b47dd214b405.png)

**Comment by RecklessPotcover** [comment]
**_Complete run sprites for Jason with a new attire._**

![main_player_attire_a_run_1](https://user-images.githubusercontent.com/31987631/135395277-148d0f0b-2d4b-4847-8452-ba5452332584.png)

![main_player_attire_a_run_2](https://user-images.githubusercontent.com/31987631/135395280-0fcb86a7-6087-4876-9899-d0234881a7c3.png)

**Comment by RecklessPotcover** [comment]
**_Completed crouch sprites for Jason with a new attire._**

![main_player_attire_a_crouch_1](https://user-images.githubusercontent.com/31987631/135452389-20a382d4-5623-4e1a-b6af-451701fa9899.png)

![main_player_attire_a_crouch_2](https://user-images.githubusercontent.com/31987631/135452393-d4ff3f99-5388-421a-b335-16565806dc2b.png)

**Comment by RecklessPotcover** [comment]
**_Completed jump sprites for Jason with a new attire_**

![main_player_attire_a_jump_1](https://user-images.githubusercontent.com/31987631/135452587-99bed76d-0f85-4cc0-8461-5f9195680793.png)

![main_player_attire_a_jump_2](https://user-images.githubusercontent.com/31987631/135452601-e37fd6ad-5e73-4239-861a-f24a65a9e430.png)

![main_player_attire_a_jump_3](https://user-images.githubusercontent.com/31987631/135452609-23fcbdf1-7b20-459e-bf68-49bc6ed0d2b5.png)

**Comment by RecklessPotcover** [comment]
**_Completed attack sprites for Jason with a new attire_**

![main_player_attire_a_attack_1](https://user-images.githubusercontent.com/31987631/135561468-457f2511-c1a1-4154-a573-7c401f8345ac.png)

![main_player_attire_a_attack_2](https://user-images.githubusercontent.com/31987631/135561472-9746b76b-17c4-485c-bac5-0462ef56d6dc.png)

![main_player_attire_a_attack_3](https://user-images.githubusercontent.com/31987631/135561474-90899f7b-7544-4cec-8931-b53df898271c.png)

**Comment by LIU-Evelyn** [comment]
**Complete idle and walk sprites for Jason with another new attire.**
_idle:_
![mpcAttire2_idle](https://user-images.githubusercontent.com/88132643/135578960-b17d529c-df7d-4e00-bcd1-fee19016c2f2.png)
_walk:_
![mpcAttire2_walk_2](https://user-images.githubusercontent.com/88132643/135579012-83fa8a10-c2b0-4d8c-a6a0-f060b81e4dca.png)
![mpcAttire2_walk_1](https://user-images.githubusercontent.com/88132643/135579020-351d0b7c-3f42-452b-8315-cb5fffa4f6a3.png)

**Comment by RecklessPotcover** [comment]
**_Completed pick up sprites for Jason with a new attire. All frames of my attire is completed._**

![main_player_attire_a_pick_1](https://user-images.githubusercontent.com/31987631/135700528-afafa0c1-081c-4af2-9959-0a29eeb66a6a.png)

![main_player_attire_a_pick_2](https://user-images.githubusercontent.com/31987631/135700529-566910be-060b-48b6-bfd7-a6cbd47f0b25.png)

![main_player_attire_a_pick_3](https://user-images.githubusercontent.com/31987631/135700532-85977ccb-b900-40ac-8e59-2067134a118f.png)

![main_player_attire_a_pick_4](https://user-images.githubusercontent.com/31987631/135700533-809fab9b-2946-4b94-92bf-1d89a67c89de.png)

**Comment by enmmjc** [comment]
Idle and Walk Status:
![main_player_pickup_4](https://user-images.githubusercontent.com/88018768/135721215-6ed9840f-ce6c-4521-b22a-efbf0a5cf39e.png)
![main_player_walk_1](https://user-images.githubusercontent.com/88018768/135721225-1e7393f2-5181-4a3d-a0d0-1b79f8c8bc54.png)
![main_player_walk_2](https://user-images.githubusercontent.com/88018768/135721234-7a5e1c1b-cbe0-4d71-b19b-29d2d409d3ae.png)

**Comment by enmmjc** [comment]
**_Player Attack Frames:_**
![main_player_attack_1](https://user-images.githubusercontent.com/88018768/135721308-26835401-8d98-4a4e-9234-c8b6fb0bd9cf.png)
![main_player_attack_2](https://user-images.githubusercontent.com/88018768/135721311-b0781677-c68f-40f7-bc96-4e6ea174d7fd.png)
![main_player_attack_3](https://user-images.githubusercontent.com/88018768/135721314-61c9cdc2-6bd8-491c-9f4d-f9edd66fd5d9.png)

**_Player Crouch Frames:_**
![main_player_crouch_1](https://user-images.githubusercontent.com/88018768/135721321-11862821-a05f-4e7b-b662-4e7f7a2ebbe2.png)
![main_player_crouch_2](https://user-images.githubusercontent.com/88018768/135721327-49284334-b1bd-4dd7-98b7-7d9aea153512.png)

**Comment by enmmjc** [comment]
_**Player Jump Frames:**_
![main_player_jump_1](https://user-images.githubusercontent.com/88018768/135721426-b2e73fbd-8240-4bcc-9cce-609fb84ef316.png)
![main_player_jump_2](https://user-images.githubusercontent.com/88018768/135721449-d21adc83-1d18-4ed8-86d2-f2a8b82164fa.png)
![main_player_jump_3](https://user-images.githubusercontent.com/88018768/135721453-443f8f6b-5ca7-4fa0-b4e7-0a0b1b67c13b.png)

_**Player Run Frames:**_
![main_player_run_1](https://user-images.githubusercontent.com/88018768/135721456-ca26decf-e2b8-4726-8f02-ab4af3203d94.png)
![main_player_run_2](https://user-images.githubusercontent.com/88018768/135721457-990fa4c2-5637-4a5b-8936-5dcfb1b582ef.png)

**Comment by enmmjc** [comment]
_**Player Pickup Frames:**_
![main_player_pickup_1](https://user-images.githubusercontent.com/88018768/135721491-560e1b28-f5c3-4eb7-979b-3955d1862c7c.png)
![main_player_pickup_2](https://user-images.githubusercontent.com/88018768/135721492-b1e3031e-9f6e-4097-8476-9fac732cd8f9.png)
![main_player_pickup_3](https://user-images.githubusercontent.com/88018768/135721494-af8fd91b-e570-4e01-ba37-e59c6bc96d73.png)
![main_player_pickup_4](https://user-images.githubusercontent.com/88018768/135721496-77b9b4a6-801e-47a1-98db-191d220fb4be.png)

**Comment by LIU-Evelyn** [comment]
**changed the image of the right side and walk/run movement:**
**_right_side:_**
![main_player_right](https://user-images.githubusercontent.com/88132643/135746842-8d6e6532-3424-41be-8e1d-9c457be53c25.png)
**_walk:_**
![main_player_walk_1](https://user-images.githubusercontent.com/88132643/135746864-7e734480-0e2c-4ff0-ab52-af816e3da41d.png)
![main_player_walk_2](https://user-images.githubusercontent.com/88132643/135746871-ebcf1444-a1d4-4a77-8026-19b7e0816dee.png)
**_run:_**
![main_player_run_1](https://user-images.githubusercontent.com/88132643/135746884-992110e0-fc8c-4525-8a04-ac3a12af55f1.png)
![main_player_run_2](https://user-images.githubusercontent.com/88132643/135746887-f76c8791-35a3-49d4-ab0b-edf9317cae76.png)

**Comment by LIU-Evelyn** [comment]
**completed the gold_4 attires for jumping:**
![main_player_jump_1](https://user-images.githubusercontent.com/88132643/135746950-ee59b2b4-944e-4dd6-afdc-a95e29536c7a.png)
![main_player_jump_2](https://user-images.githubusercontent.com/88132643/135746956-da554914-26bf-4468-8cb0-82979388e0cf.png)
![main_player_jump_3](https://user-images.githubusercontent.com/88132643/135746961-d6750253-4018-458f-90dd-75e62af54187.png)

**Comment by LIU-Evelyn** [comment]
**completed the gold_4 attires for crouching:**
![main_player_crouch_1](https://user-images.githubusercontent.com/88132643/135746979-95a856fe-b60f-4935-8ec7-52900555ffe0.png)
![main_player_crouch_2](https://user-images.githubusercontent.com/88132643/135746987-38746b61-cef6-438f-acfd-bdfaa49d6641.png)

**Comment by LIU-Evelyn** [comment]
**completed the gold_4 attires for attacking:**
![main_player_attack_1](https://user-images.githubusercontent.com/88132643/135747026-b6681391-98f5-4b14-975f-17f56fa1d53c.png)
![main_player_attack_2](https://user-images.githubusercontent.com/88132643/135747035-444e6997-eefc-4b3f-ad6f-cbeea6125ce7.png)
![main_player_attack_3](https://user-images.githubusercontent.com/88132643/135747042-13ab375f-3aff-4711-b78f-395de7f4d158.png)

**Comment by LIU-Evelyn** [comment]
**completed the gold_4 attires for picking up items:**
![main_player_pickup_1](https://user-images.githubusercontent.com/88132643/135747059-ce8262d1-ba11-43f6-b3be-a3f3151434f0.png)
![main_player_pickup_2](https://user-images.githubusercontent.com/88132643/135747069-3548e204-86ca-4ddd-a22f-31b8b60606bc.png)
![main_player_pickup_3](https://user-images.githubusercontent.com/88132643/135747081-185c5887-243b-4e0c-8447-ca25e0de6c34.png)
![main_player_pickup_4](https://user-images.githubusercontent.com/88132643/135747077-62c5b95a-db31-489f-8025-007d8eab3dd5.png)
