### ISSUE TITLE
Designing scoreboard integration related assets (Sept 21)

### ISSUE THREAD

**Issue by ThatTechedGuy** [UQdeco2800/2021-ext-studio-2#251]
# **Description**
 To display score details dialog and clickable achievement status trophies in the History Scoreboard screen. 

- Achievement status trophies should be designed to look very basic. They have to be displayed in the column beside the score in that particular row. Trophies are of 3 colors -  Bronze, Silver and Gold.   
- The dialog background needs to have a silver shade (a bit of white towards the left so that there's enough contrast with all 3 trophies). 
 
# **Dependencies**
- History Scoreboard 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Designing Bronze, Silver and Gold trophies (Sept.21)
- [x] Dialog Box (Sept.22)
- [x] Add score time calender icon(Sept.28)
 
**Completion Deadline:** Sept. 24

 
# **Documentation**
[Achievement interface improvement](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Achievement-interface-improvement)

# **Member**
- Aditya Singh Cheema (@addiii4 ) 
- Zibo Gong (@Zibo1 )

**Comment by Zibo1** [comment]
Adding score details dialog icons
