### ISSUE TITLE
Code Implementation: Spaceship Attack (Sep. 21)

### ISSUE THREAD

**Issue by lisslulay** [UQdeco2800/2021-ext-studio-2#252]
# **Description**
**Task:** [Code Implementation: Spaceship Scenes](#252).
**Feature:** [Spaceship (map entrance keeper)](#242)

Use code to implement the scenario of a spacecraft attack.
 

# **Milestones**
- [x] Code implementation: Prohibit left and right
- [x] code implementation: camera lens, character position
- [x] code implementation: missile initial velocity, gravity
- [x] Code implementation: spaceship does not overlap with other obstacles/enemies
- [x] code implementation: the spacecraft launching missile position, number, time
- [x] restart bug
 
**Completion Deadline:** Sep. 21

 
# **Documentation**
- [Game Play of Obstacles](../wikis/Obstacles-Gameplay)
- [Code Guidelines of Spaceship Boss ](../wikis/Spaceship-Boss-Code)
 
# **Members**
- Shanshan (@lisslulay) (Shanshan Li)
