### ISSUE TITLE
Implementation of map entry transfer (Sep. 25)

### ISSUE THREAD

**Issue by lisslulay** [UQdeco2800/2021-ext-studio-2#253]
# **Description**
**Task:** [Code Implementation: Spaceship Scenes](#252).
**Feature:** [Spaceship (map entrance keeper)](#242)

Use code to realize characters crossing between different maps.
 
# **Dependencies**
- [x] The new map position in the game (#233)

# **Milestones**
- [x] code implementation: place portals in origial map
- [x] code implementation: place portals in new map
- [x] code implementation: camera lens shift
- [x] code implementation: character position transfer

**Completion Deadline:** Sep. 25

 
# **Documentation**
- [Game Play of Obstacles](../wikis/Obstacles-Gameplay)
- [Code Guidelines of Spaceship Boss ](../wikis/Spaceship-Boss-Code)
 
# **Members**
- Shanshan (@lisslulay) (Shanshan Li)
