### ISSUE TITLE
Team 4 Task Ticket 1 - Determine the basic image of the character

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2021-ext-studio-2#26]
# **Description**
**Task:** [ Determine the basic image of the character](#26)
**Feature:** [Team 4 Feature Ticket - Main Player Character](#6)

Determine the image of the main player character and possible interactive actions based on the style and settings of the entire game.
 
## **Example (optional)**

- Determine the image of the main character and the style of painting.
- Combine other features to determine all the state that appears in the state machine, e.g. what behaviours and activities the protagonist can have, and determine the feasible range.
- Communicate with other teams to get a better idea of their features.

 
# **Dependencies** 
There are a few tasks that will be the dependencies of our task:
- [x] The design of obstacles affects our decisions about how characters interact with them. (#14)
- [x] How the character moves in the game will affect the image design of the character when it moves. (#5)
- [x] Other factors that may affect the character's standing state. (#18) (#7)
 
# **Tasks**
Detailed task description:
- [x] Task 1.1: Discuss and confirm the character image and painting style.
- [x] Task 1.2: Communicate with other teams to confirm their features.
- [x] Task 1.3: Determine what possible actions the main character might have when interacting with other game features, and what it looks like. 
 
# **Milestones**
List of steps that need to be completed for this task:
- [x] Task 1.1 (Aug. 18)
- [x] Task 1.2 (Aug. 18)
- [x] Task 1.3 (Aug. 18)

**Completion Deadline:** Aug. 19

 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Jiacheng Ni - @RecklessPotcover (Alex)
- Jescy Xu - @enmmjc 
- Yingxin Liu - @LIU-Evelyn

**Comment by LIU-Evelyn** [comment]
Based on the example of the game engine given and combined with the story background, we decided to design the protagonist as a middle-aged male, and tentatively design the style as pixel & cartoon. 
After discussing with the Team 8, we found that they initially wanted to make some random obstacles fixed on the map, and the obstacles could slow down the player who touched it. Therefore, we will design three types of character images with different action states, when standing on standby, when moving, and when hitting an obstacle. (Note: including successfully avoiding obstacles when moving)
