### ISSUE TITLE
Design obstacles

### ISSUE THREAD

**Issue by HKeG** [UQdeco2800/2021-ext-studio-2#27]
# **Description**
**Task:** [Design obstacles](#27 ).
**Feature:** [Random obstacles](#14 )

Design specific functions and UI for game obstacles. 
Provide obstacle updates for the game.
 

# **Dependencies**
- [x] Obstacle effect (#6 )(#7  )

 
- [x]  Generate new obstacle types (#5  )
# **Milestones**
- [x] Design the function of the first obstacle (Aug. 20)
- [x] Design the UI of the obstacle (Aug. 23)
- [x] Make the UI of the game obstacles (Aug. 29)
- [x] Write wiki and finish the user test (Aug. 29)
 
**Completion Deadline:** Aug. 30

# **Documentation**
- [Game Play of Obstacles](../wikis/Obstacles-Gameplay)
- [Design of Obstacles](../wikis/Obstacles)
- [Code Guidelines of Obstacles](Obstacles-Code)
 
# **Member**
- Haoke  (@HKeG ) (Haoke Sheng)
& The generation and effect of obstacles
