### ISSUE TITLE
Team 6 Sprint 3 - Task Ticket - Invisible ceiling

### ISSUE THREAD

**Issue by yzy98** [UQdeco2800/2021-ext-studio-2#276]
# **Description**
**Task:** [Team 6 Sprint 3 - Task Ticket - Invisible ceiling](#3).
**Feature:** [Team 6 Sprint 3 - Feature Ticket - Game environment optimization](#https://github.com/UQdeco2800/2021-ext-studio-2/issues/232)

Implement an invisible ceiling to the game to prevent the player jumping out of the game screen. The ceiling needs to be invisible and cannot be passed through by the player.
 
# **Dependencies**
Consider team 8's obstacles should not be collided with the ceiling.

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Confirm ceiling position and range (Sep. 17)
- [ ] Come up with invisible ceiling mechanism (Sep. 24)
- [ ] Collaborate with team 8 on obstacle can pass through the ceiling (Sep. 25)
- [ ] Code implementation (Sep 28)
- [ ] Unit test (Sep. 30)
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitLab Username) (Slack Handle)
- Richard (@AppleByter) (Richard Thomas)
- Zi Yang(@yzy98) (Zi Yang)
- Yuqi Yang(@Marco777777)(Yuqi Yang)
- Yinghao Fu(@katrinafu1 ) (Katrina Fu)
