### ISSUE TITLE
 New map background & terrain implementation

### ISSUE THREAD

**Issue by yzy98** [UQdeco2800/2021-ext-studio-2#277]
# **Description**
**Task:** [Team 6 Sprint 3 - Task Ticket - New map background & terrain implementation](#3).
**Feature:** [Team 6 Sprint 3 - Feature Ticket - Multiple Maps](#233)
 
Rendering a new background and terrains when entering the new map, which is a bonus map for the player to gain more coins and scores. 
 
# **Dependencies**
 
- [ ] The new map entrance (#253 )

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Background image and terrain design (Sep. 24)
- [ ] Collaborate with team 8 on new map entrance (Sep. 26)
- [ ] Code implementation: background scrolling image and road terrain(Sep. 28)
- [ ] Unit test (Sep. 30)
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitLab Username) (Slack Handle)
- Richard (@AppleByter) (Richard Thomas)
- Zi Yang(@yzy98) (Zi Yang) 
- Yuqi Yang(@Marco777777) (Yuqi Yang)
- Yinghao Fu(@katrinafu1 ) (Katrina Fu)
