### ISSUE TITLE
New map rocks and woods generation

### ISSUE THREAD

**Issue by yzy98** [UQdeco2800/2021-ext-studio-2#279]
# **Description**
**Task:** [New map rocks and woods generation](#3).
**Feature:** [Team 6 Sprint 3 - Feature Ticket - Game environment optimization](#232 )
 
Generating some rocks and woods in the new map. These rocks and woods require to be piled up in order in order to allow the player to jump on to pick up coins.
 
# **Dependencies**

- [ ] Team 1 new map coins generation (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Design the basic types of rocks and woods pile (Sep. 24)
- [ ] Create the mechanism of piling up rocks and woods (Sep. 26)
- [ ] Code implementation (Sep. 28)
- [ ] Collaborate with team 1 on coin generation (Sep. 30)
- [ ] Unit test (Oct. 1)
 
**Completion Deadline:** Oct. 1

 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitLab Username) (Slack Handle)
- Richard (@AppleByter) (Richard Thomas)
- Zi Yang(@yzy98) (Zi Yang)
- Yuqi Yang(@Marco777777)(Yuqi Yang)
- Yinghao Fu(@katrinafu1 ) (Katrina Fu)
