### ISSUE TITLE
Team 5 Sprint 3 Task Ticket - Item bar and recycle system UI design

### ISSUE THREAD

**Issue by TerrestrisYE** [UQdeco2800/2021-ext-studio-2#281]
# **Description**
**Task:** [Item bar icon and recycle system UI design](#3)
**Feature:** [Item bar](https://github.com/UQdeco2800/2021-ext-studio-2/issues/8) & [Recycle system](https://github.com/UQdeco2800/2021-ext-studio-2/issues/239)
 
Creat assets for item bar and recycle system.

# **Dependencies**
 None
 
# **Milestones**
List of assets that need to be completed for this task.
*Draft design: (9.27)*
- [x] Ham icon draft
- [x] Water icon draft
- [x] Blood bag icon draft
- [x] Recycle system UI draft

*User testing: (9.30)*
- [x] Ham icon
- [x] Water icon
- [x] Blood bag icon
- [x] Recycle system UI

*Finalizing assets: (10.)*
- [x] Ham icon
- [x] Water icon
- [x] Blood bag icon
- [x] Recycle system UI

**Completion Deadline:** 
 
# **Documentation**
- None
 
# **Member**
- YE Lingfeng (@TerrestrisYE) Lingfeng YE
- @Noarrrr (Keyu Bai)
