### ISSUE TITLE
Game story integration and chapter art - Sprint 3

### ISSUE THREAD

**Issue by ThatTechedGuy** [UQdeco2800/2021-ext-studio-2#284]
# **Description**
 
Each chapter documented will have a chapter art which depicts the main events occurring in that particular chapter.

The game story that has been developed in sprint 2 needs to include each and every aspect about the game. During sprint 3, new obstacles were added to the game by team 8. The obstacles added (spaceship boss, wormhole) needed to be addressed in the game story for enhanced background of the game. Collaboration was done with team 8 to add these aspects in the story with regards to the gameplay. 
 
# **Dependencies**
No dependencies.

# **Milestones**
List of steps that need to be completed for this chapter art.
- [x] Chapter art for the first 2 chapters (Oct. 4)

**Completion Deadline:** Oct. 4

List of steps that need to be completed for this game story integration.
- [x] Story draft reviewed by team 8 (Sept. 25)
- [x] Comments and suggestions added (Sept. 27)
- [x] Final draft documented on wiki (Sept. 29)
 
**Completion Deadline:** Sept. 30
 
 
# **Documentation**
- [Game story chapters](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Chapters)
- [Google doc draft](https://docs.google.com/document/d/1FwDNmEhNLfvZli3zpIK6qjbi2iRHCM095yEjXAl1YcI/edit)
 
# **Member**
- Aditya Singh Cheema (@addiii4 )      - Team 7
- Shanshan (@lisslulay )      - Team 8

**Comment by lisslulay** [comment]
The monster manual may be related to the story. We expect to give each obstacle or enemy a story background (such as where the monster came from, etc.), which is expected to be displayed in the monster manual. The background story of entities will be designed by our team members, but I hope this is consistent with the background 
of the big story. 
We may add a very big boss - a spaceship in sprint 3. The current design is that this boss will make the character pause for a few seconds. In these few seconds, the character will jump up and down to avoid the spaceship's attack. We are here to show that we will add spaceships in the game, which should be related to the current story background.

**Comment by addiii4** [comment]
Alright we’ll make the changes to the story and let you review it.

**Comment by lisslulay** [comment]
Thanks.

**Comment by lisslulay** [comment]
Hello, after discussion between team8 and team6, it is decided that the spaceship boss will exist as the guardian of the new map. When the character survives the boss attack, a new map entrance will appear. Maybe this setting will affect the storyline.

**Comment by addiii4** [comment]
We’ve made the changes and here’s the link to the google doc
https://docs.google.com/document/d/1FwDNmEhNLfvZli3zpIK6qjbi2iRHCM095yEjXAl1YcI/edit 
@Butcanudothis

**Comment by lisslulay** [comment]
We’ve made some edits. Please review. @addiii4

**Comment by addiii4** [comment]
Looks good. We will commit these updates to the main game soon.

**Comment by ThatTechedGuy** [comment]
Update: The game story is finally complete, as can be seen in the Google Doc. The game story and chapter arts 1 - 5 will be added as soon as Sprint 4 starts. A new game story collaboration task ticket will be made for Sprint 4. Team 7 will not be taking any more story amendment requests in this ticket. Thankyou!
