### ISSUE TITLE
Redesigning older assets  (Sept 21)

### ISSUE THREAD

**Issue by Kaiwang4** [UQdeco2800/2021-ext-studio-2#286]
# **Description**
**Feature:** [Achievement Integrations with other features](#286)
 
After conducting a survey and online interviews, we summarized the comments on the design of achievement trophies and achievement cards. Also, after discussion within the group, we decided to redesign all achievement trophies and cards. The redesigned achievement trophies and cards maintain the simplicity of the previous version, but the pixel points have been polished carefully to make the design look simple and exquisite. In addition, the design concept of achievement trophies and cards remains the same as the previous version, with each trophy and card divided into three versions: gold, silver and bronze, with gold trophies accounting for the largest proportion of the cards and bronze trophies the smallest.

 
# **Dependencies**
No dependencies on which this ticket relies. 
 

 

 
# **Milestones**
Redesigns for Healer, Master, Veteran, Tool Master, Game Breaker and Stranger achievements. 
List of steps that need to be completed for this task.
- [x] redesign 18 cards (Sept. 24)
- [x] redesign 18 trophies (Sept. 25)
- [x] write feature design documentation (Sept. 28)
 
**Completion Deadline:** Sept. 28
 
 
# **Documentation**
- [Achievements Trophies and Cards Design](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Achievements-Trophies-and-Cards-Design)

# **Member**
- Kai Wang (@Kaiwang4)

**Comment by Kaiwang4** [comment]
Documentation subtask added

**Comment by Butcanudothis** [comment]
Documentation added by Kai Wang
