### ISSUE TITLE
Assets for new achievements

### ISSUE THREAD

**Issue by Butcanudothis** [UQdeco2800/2021-ext-studio-2#297]
# **Description**
**Feature:** [Achievement Integrations with other features](#236 )
 
This task involves addition of assets as per the new standard following the redesign of older achievements. The new achievements added in this sprint are Game Fanatic, Collector, Survival Expert and Alphamineron

# **Dependencies**
Depends on the following tasks :
- [x] new redesigned assets for design consistency. #286 
 
 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Designs for Game Fanatic, Collector and Survival Expert.
- [x] Designs for Alphamineron achievement @Butcanudothis  (Aug. 20)

 
**Completion Deadline:** Sept 30
 
 
# **Documentation**
[Game-achievements](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Game-achievements)
[Achievement trophies and cards](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Achievements-Trophies-and-Cards-Design)

# **Member**
- Akshay Varma (@Butcanudothis )
- Kai Wang (@Kaiwang4 )
