### ISSUE TITLE
Team 9 Feature Ticket - Scoring System

### ISSUE THREAD

**Issue by Noarrrr** [UQdeco2800/2021-ext-studio-2#3]
# **Description**
Scoring system is related to WIN 🏆 or LOSE 😑. Friends can compare their scores after playing. The scoring system records the player's score from the beginning till the end of the game. There are many actions are related to player's score. 

Since the game is an infinite looping game #5, we will build a timing system. The game duration is the main parameter for the scoring system. In this first sprint. We will only use "TIME" as the scores. 

This sprint: 
Scoring calculation: Final Score = Time in seconds. 

Future Sprints: 
Scoring calculation (will be updated in each sprint): Final Score = Time in seconds + Items in the bag system * x (some values) + achievments * y(some values). 
 
## SubFeature/component (optional)
A timing system & An interface --- just a small box in the game screen

# **Dependencies**
1. The nature of the game (game story). Can be found here. (https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Game-Story)
2. Player's health status. #7  and #5 need to know when the game is over so that the timer stops. 
Future sprints:
1. The bag system #8 
2. The achievments #4 
 
 
# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Have a read through the wiki page.
- [x] Understand some basic engine stuff.
- [x] Implement the timing system. #16 (pure logic)
- [x] Design and build the interface of displaying the score in the game. #21 (pure UI)
- [x] Notify the teams who need the score after finish.  
- [x] Design the clock icon and score board.
- [ ] Write some JUnit tests
- [x] Add more parameters to the score if there is time left. 
 
**Completion Deadline:** (Date)
 29 Augest --- Few days before the end of the first sprint. 
# **Extras (optional)**
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [User documentation](../../wikis/Game-Guide#section1)
- ...
 
# **Members**
(Git hub name)(Slack name)
- @Bohan-is-in-the-zone (Bohan Xu)
- @YiYang200 (Yi Yang)
- @Noarrrr (Keyu Bai)
- @yungseop (YoungSeob Lee)
- @pranavdhoolia (Pranav Dhoolia)

**Comment by uqtnieva** [comment]
I would recommend speaking to team 6 on who is implementing the timing system. Though, I think this is something your team should be taking on. You might also want to speak to team 1 about what types of items they will be implementing.

Also, there is no team implementing "Alien Enemies or Bosses" so I would recommend removing this from your ticket/scoring system at the moment. This could be a future feature.

Other than that, looks good!

**Comment by Bohan-is-in-the-zone** [comment]
> I would recommend speaking to team 6 on who is implementing the timing system. Though, I think this is something your team should be taking on. You might also want to speak to team 1 about what types of items they will be implementing. It seems they are thinking of adding in a gold coin - perhaps you could include this in your scoring?
> 
> Also, there is no team implementing "Alien Enemies or Bosses" so I would recommend removing this from your ticket/scoring system at the moment. This could be a future feature.
> 
> Other than that, looks good!
