### ISSUE TITLE
Team 4 Task communication: Design Buff/debuffs animation and integration 

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2021-ext-studio-2#319]
# **Description**
**Task:** [Design Character's Functionality Aesthetics](#273)
**Feature:** [Team 4 Sprint 3 Feature Ticket 1: Functionality Integration of attack, item pickup, buffs/debuffs with MPC](#230)

For task communication and cooperation with Team 3. We will design and improve the buff animations displayed on the characters' frames according to the progress of both teams, and update the results and progress in this ticket in time.
 
## **Example (optional)**

- The main character of each suit needs a full set of buff animations.
- When the main character touches a specific buff, the buff will be shown being applied by floating behind the main character (The upper left corner, 100*100 pixel).

# **Dependencies** 
- Buffs and debuffs provided by Team 3 - was decided that Team 3 will provide the list of buffs available, and our team is in charge of implementing the buffs onto the main character by drawing the buffed-mode character in Illustrator. (#10)

 
# **Tasks**
Detailed task description.
- [x] Task 1.1: Communicate with Team 3 and integrate the buff/debuffs and characters.
- [ ] Task 1.2: Complete the buff animation design of the original character.
- [ ] Task 1.3: Completed the buff animation design for characters that unlocked the Gold_2 attires.
- [ ] Task 1.4: Completed the buff animation design for characters that unlocked the Gold_4 attires.
- [ ] Task 1.5: Completed the buff animation design for characters that unlocked the Gold_6 attires.
- [ ] Task 1.6: Make sure the design of the image is consistent and complete the image design required for the game.
# **Milestones**
List of steps that need to be completed for this task.
- [x] Task 1.1 (Sept. 29)
- [x] Task 1.2 (Oct. 03)
- [ ] Task 1.3 (Oct. 03)
- [ ] Task 1.4 (Oct. 03)
- [ ] Task 1.5 (Oct. 03)
- [ ] Task 1.6 (Oct. 03)

**Completion Deadline:** Oct. 04

 
# **Documentation**
- [Main description of feature](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Main-Character)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ... 

# **Member**
- Jiacheng Ni - @RecklessPotcover (Alex)
- Jescy Xu - @enmmjc 
- Yingxin Liu - @LIU-Evelyn 
- Zhenyu Ding - @7ayuu

**Comment by prateek45** [comment]
Team 4 has implemented the buff/debuff animations for MPC Gold_6 attire.

**Comment by LIU-Evelyn** [comment]
Team 4 has implemented the buff/debuff animations for MPC original attire.

**Comment by 7ayuu** [comment]
Team 3 has implemented the buff/debuff animations for MPC Gold_4 attire.

**Comment by LIU-Evelyn** [comment]
There are 153 buff/debuff frames for each attire.
