### ISSUE TITLE
Team 3 Task Ticket - Determine the show of Buffs/Debuffs

### ISSUE THREAD

**Issue by 7ayuu** [UQdeco2800/2021-ext-studio-2#32]
# **Description**
**Task:** [ Determine the show of Buffs/Debuffs ](#32)
**Feature:** [ Team 3 Feature Ticket - Buffs/Debuffs ](#10)

Determine the image of Buffs/Debuffs and the interactions with the characters created based on the style and setting of the entire game.  
 
## **Example (optional)**

- Determine the show of the Buffs/Debuffs. 
- Combine the properties of the buffs/debuffs to determine their appearance image, e.g. When the item's property is to increase defense, the image of a shield surrounding the character will appear.  
- Communicate with other teams to get a better idea of their features.

 
# **Dependencies** 
There are a few tasks that will be the dependencies of our task:
- [ ] The design of the items will affect our setting of buffs. (#9 )
- [ ] The design of the obstacles will affect our setting of debuffs.  (#14 )
- [ ] The set painting part of the character state will affect our design of the appearance of buffs/debuffs. 
 (#7 )
 
# **Tasks**
Detailed task description:
- [ ] Task 1.1: Discuss and confirm the show of buffs/debuffs.  
- [ ] Task 1.2: Communicate with other teams to confirm their features for determine the data for buffs/debuffs.  
- [ ] Task 1.3: Determine how the appearance of buffs/debuffs will affect the manifestation of the character after it is acquired. 
 
# **Milestones**
List of steps that need to be completed for this task:
- [ ] Task 1.1 (Aug. 19)
- [ ] Task 1.2 (Aug. 19)
- [ ] Task 1.3 (Aug. 19)

**Completion Deadline:** Aug. 20

 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Aditya Samuel Hadinata(@AdityaSHadinata) 
- Zhenyu Ding (@7ayuu) 
- Zewei Zhu (@EricZhu123)  
- Wei Liu (@WeiLIU01)

**Comment by 7ayuu** [comment]
have finish the task1.1 and task1.2
