### ISSUE TITLE
Team 4 Task Ticket 3 - Implementation of character movement and actions

### ISSUE THREAD

**Issue by kprohith** [UQdeco2800/2021-ext-studio-2#33]
# **Description**
**Task:** [Implementation of character movement and actions](#33).
**Feature:** [Main Player Character](#6 )
 
This function will be dedicated to the realization of the protagonist of the game, including the protagonist’s aesthetic image and the change of the image when doing actions. We need to consider the interactions it needs to perform when avoiding obstacles (or picking up props), and how these interactions will affect its appearance when moving along the path. Therefore, it is also necessary to determine the different images of the main character due to changes in their action (state) during the interaction process. Each image should clearly correspond to a different interaction state.

- [x] Position character in a blank map with a side-scrolling perspective 
- [x] Implement movement - left, right, up, down
- [x] integrate with the procedural map generation/pathway generation component when ready
- [x] Implement character movement animation

# **Dependencies**
- Obstacles implementation - affects the realization of the player's interaction with obstacles. (#14)
- The image of the character depends on the interaction and the status of the character while running. (#9) (#7)
- Infinite game loop, map generation, and pathway creation. (#24)
- Buffs/Debuffs (#10) 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 Understand the workings of the game engine and review the codebase (Aug.21)
- [x] Step 2 Implement and adjust the positioning of the main player character in the map. (Aug. 23)
- [x] Step 3 Implement main player character movement. (Aug. 31)
- [x] Step 4 Create texture atlas to implement dynamic switching of character view, depending on direction of movement. (Aug. 31)
- [x] Step 5 Implement animation handler to integrate the texture atlas onto the main player entity. (Aug. 31)
- [x] Step 6 Implement walking animation. (Aug. 31)
- [x] Step 7 Implement running animation. (Aug. 31)
 
**Completion Deadline:** Aug. 31
 
 
# **Documentation**
[Main Character](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Main-Character)

# **Member**
- Rohith Palakirti (@kprohith)
- Prateek Kumar Gupta (@prateek45)
