### ISSUE TITLE
Team-1 Sprint 3 UI Design of Props Store

### ISSUE THREAD

**Issue by LiwenJin2829** [UQdeco2800/2021-ext-studio-2#345]
# **Description**
This task is to improve the user interface of the props store. We are going to design a background image for the props store and adjust the layout of the interface, including buttons, items and the text style.

## **Examples**
- **Food**: Items that restore hunger value
- **Health**:Items that restore health value
- **Background Image**: A pixel-style shelf with items that can be purchased

# **Dependencies**
Player Status: The number of items depend on the type of buff and debuff(#10 ).

# **Milestones**
- [ ] Design the background image(Sep. 20)
- [ ] Adjust the buttons, items and other elements (Sep. 24)
- [ ] Adjust the layout (Sep. 28)
- [ ] User testing & documentation.(Oct.04)

# **Documentation**
- [Main description of feature](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Prop-store-layout)
- [User documentation](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Props-store-user-testing)

# **Members**
- Jiahe ZHAO(@PaddyZz)
- Liwen Jin(@LiwenJin2829)
- Yuehan Xu (@johnxu7)
