### ISSUE TITLE
Settings Screen redesign and improvements

### ISSUE THREAD

**Issue by Butcanudothis** [UQdeco2800/2021-ext-studio-2#366]
# **Description**
This feature involves redesign for the settings screen GUI to match the design consistency of the game. It will also involve a better user interface along with additional relevant settings like music selection for each screen. These settings will be reflected across all screens and will be in sync with them. 
 
## SubFeature/component (optional)
- GUI Assets for settings screen
- `settings.json` changes
- User Testing  the settings screen improvements
 
# **Dependencies**
 These dependencies were recognized
 #364 
 #361 
 
# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] GUI Assets for settings screen
- [ ] `settings.json` changes
- [ ] User Testing  the settings screen improvements
 
**Completion Deadline:** Oct 9
 
# **Documentation**
To be added
 
# **Members**
- Vishal Gupta (@ThatTechedGuy )
- Akshay Varma (@Butcanudothis )
- Kai Wang (@Kaiwang4 )
- Zibo Gong (@Zibo1 )
- Aditya Singh Cheema (@addiii4 )

**Comment by Butcanudothis** [comment]
@7ayuu since you have closed #413, but had committed some of the assets in the PR #414 We'll use some of them in our settings implementation. This should count towards cross team collaboration. we can add team 3 to #368.
