### ISSUE TITLE
Team 3 - Sprint 4 - Feature - Game Tutorial Refinement Feature Ticket

### ISSUE THREAD

**Issue by EricZhu123** [UQdeco2800/2021-ext-studio-2#367]
# Description
This feature is set to make refinement of the implemented Game Tutorial page to ensure this page can cooperate with the overall style of the game.

# Subfeature/ Component 
- Change the background of the game tutorial page.
- Change the font style of the game tutorial page.

# Milestone
- [ ] Design the updated version of the instruction-related buttons and pages (Oct.16)
- [ ] Reconsider and make the tutorial contents (Oct.16)
- [ ] Add them to the game (Oct.18)

**Test and evaluation deadline (Oct. 19)**

# Members
- Zewei Zhu (@EricZhu123 )
- sumermakhija (@sumermakhija )

**Comment by uqtnieva** [comment]
You can list this improvement in the old ticket instead of creating a new one. Just make it clear what the improvement is (in a comment or new section) and add new milestones.
