### ISSUE TITLE
GUI Assets for settings screen

### ISSUE THREAD

**Issue by Butcanudothis** [UQdeco2800/2021-ext-studio-2#368]
# **Description**
**Task:** [GUI Assets for settings screen](#3).

To make the whole game look more coherent, we have optimized the setting part of the game. First of all, we designed icons for each column of settings. Each icon includes the state when it is triggered and the state when it is not triggered. Secondly, we redesigned the background of the whole setting interface to make it match the style of the game.
 
 
# **Dependencies**
No dependencies.
 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add new icons for settings (Oct. 9)
- [x] Design new setting background (Oct. 10)
- [x] Discuss and select the best background scheme (Oct. 11)

 
**Completion Deadline:** Oct. 11
 

 
# **Member**
- Zibo (@Zibo1 ) (Zibo Gong)
- Kai Wang (@Kaiwang4) (kai wang)
