### ISSUE TITLE
Locate the player's coordinates 

### ISSUE THREAD

**Issue by YuanyeZhang** [UQdeco2800/2021-ext-studio-2#37]
# **Description**
**Task:** [track the location of player ](#3).
**Feature:** [Locate the player's coordinates ](#2)
 
Generate a coordinate that represents the current position of the player
 
## **Example (optional)**
- **Part**:  As the player moves, the coordinates change accordingly
 
# **Dependencies**

 
- [ ] When the player coordinates coincide with the obstacle coordinates, it means the obstacle has been touched.  (#14 )
- [ ] When the player coordinates coincide with the items coordinates, he may pick up the items (#9 )
 

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Aug. 19)
- [ ] Step 2 (Aug. 20)
- [ ] Step 3 (Aug. 23)
- [ ] Step 4 (Aug. 23)
 
**Completion Deadline:** Aug. 23
 
e.g.
- [ ] Initial design of `Armour` created and documented on wiki (Aug. 19).
- [ ] Unit tests implemented for `Armour` (Aug. 20).
- [ ] `Armour` class implemented and tested (Aug. 23).
- [ ] Documentation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitLab Username) (Slack Handle)
- Richard (@AppleByter) (Richard Thomas)
