### ISSUE TITLE
Team 5 - Sprint 4 - Task - Item bar assets rework

### ISSUE THREAD

**Issue by TerrestrisYE** [UQdeco2800/2021-ext-studio-2#378]
# **Description**
**Task:** [Item bar assets rework](#378).
**Feature:** [Itembar system assets rework](#377 )
 
Based on the aesthetic design of the itembar system in Sprint 3, optimize existing assets or seek other aesthetic styles, design new drafts, and select the best solution through user testing.
 
# **Dependencies**

- None
 
# **Milestones**
- [x] Itembar rework draft (Oct. 13)
- [x] Itembar rework draft user testing (Oct. 15)
- [x] Itembar rework finalization (Oct. 16)
 
**Completion Deadline:** Oct. 16
 
# **Documentation**

- None

 
# **Member**
- YE Lingfeng (@TerrestrisYE) Lingfeng YE
- @Noarrrr (Keyu Bai)
