### ISSUE TITLE
Team 5 - Sprint 4 - Task - Recycle system assets rework

### ISSUE THREAD

**Issue by TerrestrisYE** [UQdeco2800/2021-ext-studio-2#379]
# **Description**
**Task:** [Recycle system assets rework](#379)
**Feature:** [Itembar system assets rework](#377 )
 
Based on the aesthetic design of the recycle system in Sprint 3, optimize existing assets or seek other aesthetic styles, design new drafts, and select the best solution through user testing.
 
# **Dependencies**

- None

# **Milestones**
- [x] Recycle system rework draft (Oct. 13)
- [x] Recycle system rework draft user testing (Oct. 15)
- [x] Recycle system rework finalization (Oct. 16)
 
**Completion Deadline:** Oct. 16
 
# **Documentation**
- [Skeuomorphic Design — A controversial UX approach that is making a comeback](https://medium.muz.li/skeuomorphic-design-a-controversial-ux-approach-that-is-making-a-comeback-a0b6e93eb4bb)
 
# **Members**
- YE Lingfeng (@TerrestrisYE) Lingfeng YE
- @Noarrrr (Keyu Bai)
