### ISSUE TITLE
Team5 sprint4 task ticket - item bar and recycle system debug and sound effects

### ISSUE THREAD

**Issue by yu-ang-zhang** [UQdeco2800/2021-ext-studio-2#380]
# **Description**

After sprint 3 the item bar and recycle system were not working well, after picking up one item the item number in item bar and recycle system will increase by two, should be fixed.
Also we will implement the item bar sound effects, then if player use items in item bar, there will be a sound effect.
 
# **Dependencies**

- None

# **Milestones**
- [x] Recycle system debug (Oct. 13)
- [x] Item bar debug (Oct. 13)
- [x] Item bar sound effects (Oct. 13)
 
**Completion Deadline:** Oct. 16
 
# **Documentation**

 
# **Members**
- Yuang Zhang (yu-ang-zhang)
