### ISSUE TITLE
Team 4 Sprint 4 Feature Ticket: Player Refinement

### ISSUE THREAD

**Issue by enmmjc** [UQdeco2800/2021-ext-studio-2#383]
# Description
This feature is dedicated to the integration and refinement of the MPC. This includes resizing the MPC to fit the entire game, fixing the frames that are bugging also completing the buff integrations that were left from Sprint 3. The main focuses of this ticket are highlighted in the bullet points down below.
- The main player seems to be needing a resize to fit the entire game.
- Fixing the frames that need to be smoothed out, as well as the frames that required posture corrections. 
- The buff animations are required to be finalized so that it doesn't run into an error when multiple buffs are collected. 
It is necessary to conduct a refinement action in order to provide users with the best gaming experience.

# Sub Features & Components
The sub-features and components include the leftover tasks from Sprint 3.
- Buff animation frames finalization. 
- Resizing MPC frames.
- Smooth and correcting certain postures.

# Examples
- The MPC size should fit the game.
- The MPC's buffed and debuffed animation should change smoothly without error. 
- The MPC should have no weird postures. 

# Dependencies
- The background of the game - required the size of the background of the game to decide the size of our MPC. (#374)
- The buff and debuff images - given during Sprint 3. (#376) 

# Task Tickets
- [x]  #426 
- [x]  #425 
- [x]  #452
- [x] #429
- [x] #431
- [x] #427
# Milestones
## Sprint 4 [06-10-2021 to 20-10-2021]
Finalization and refinement of the MPC.
- [x] Goal 1 - Complete all the buff and debuff animation frames.
- [x] Goal 2 - Communicate with the background team and decide the final size of the MPC.
- [x] Goal 3 - Resize the MPC to improve the game experience if needed. 
- [x] Goal 4 - Refine MPC movement and postures. 

**Test and evaluation deadline (Oct. 18)**

# Members
- Prateek Kumar Gupta - @prateek45
- Rohith Palakirti - @kprohith 
- Jiacheng Ni - @RecklessPotcover (Alex)
- Jescy Xu - @enmmjc 
- Yingxin Liu - @LIU-Evelyn
