### ISSUE TITLE
Team-1 Sprint 4 Optimization of item drops and propStore

### ISSUE THREAD

**Issue by LiwenJin2829** [UQdeco2800/2021-ext-studio-2#396]
# **Description**
In the first three sprints, we made some items that were dropped in the game, and players can pick them up in the game. In addition, we have added a prop store and implemented the function of the prop store. The purchase of props will take effect in the next round of the game. In Sprint 4, we will enrich the content of these two features from both the function and design aspects to enrich the player's gaming experience. This page is about Item drops.

## SubFeature/component (optional)
- Randomising Item drops
- Adding different buffs on different Items
- Refactoring ItemDrop On achievement

 
## **Examples (optional)**
- **Buff&Items**:  We need to add more effects on related items. The effect of the specific buff depends on team 3.
- **prop store background**: When users purchase props, they will see a variety of background images, such as selecting goods, purchasing and confirming. We need to add and change the background of the prop store to make it more suitable for game themes and design specifications.
-**Adding sound effects** ：There is no sound when users purchase props or hover on them. We need to add sound effects to make the purchase process more interesting and attractive.

# **Dependencies**
- **Buffs and Debuffs**: the buffs and debuffs design and ideas need to be in line with the (#10) 

 
# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Randomising Item Drops
- [ ] Improving item drop on Achievement
- [ ] User testing & documentation 
 
**Completion Deadline:** Oct.19
 

# **Documentation**
- [Main description of feature](../../wikis/page1)
- [User documentation](../../wikis/Game-Guide#section1)
- ...
 
# **Members**
- Name (GitLab Username) (Slack Handle) -- only one is needed if they are the same.
- Pranoy Sarkar(@Yonarp)
- Jiahe ZHAO(@PaddyZz)
- Liwen Jin(@LiwenJin2829)
- Yuehan Xu (@johnxu7)

**Comment by uqtnieva** [comment]
Hi Team 1, Item Drops and Prop store are separate features so they should be on separate feature tickets. I would recommend:
- Add the improvements to the relevant previous feature ticket. Make sure to make it clear what the improvement is and justification for improvement i.e. new section or in the comments.
- Update the milestones to the ticket to reflect the improvement as well. 
- Move the ticket back to the 'In Progress' column.
