### ISSUE TITLE
Design chooser GUI assets

### ISSUE THREAD

**Issue by ThatTechedGuy** [UQdeco2800/2021-ext-studio-2#399]
**Feature:**: #364 

# **Description**
To design and upload assets for the music selection chooser GUI. This involves creating :-
- **Chooser GUI Dialog Background**: Beautiful dialog background with a music icon
- **Radio buttons**: Radio buttons consistent with the rest of the game GUI. (On and Off states)
- **Music icon button**: This button will be shown in each screen, so that the user can click on it and change the background music for that particular screen. 
 
# **Dependencies**
- Background music (in game and for all screens) #385 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design dialog background
- [x] Design clickable music icon button
- [x] Design radio button (on and off state)
 
**Completion Deadline:** Oct. 13

# **Documentation**
- To be added

# **Member**
- Akshay Varma (@Butcanudothis)
