### ISSUE TITLE
Rearrangment of the rocks and woods

### ISSUE THREAD

**Issue by katrinafu1** [UQdeco2800/2021-ext-studio-2#405]
# **Description**
**Task:** Rearranment of how the rocks and woods spawn.
**Feature:** [Game environment optimization](#232 )
 
We discovered that the previous rocks and woods are not combined very well, because sometimes the player will stuck between the rocks and woods while they are jumping. So we decided to refactor the layout of the rocks and woods combine with new terrain which are magma and nails.
 
## **Example (optional)**
- **Refactor the layout of the rocks and woods**: Distance between each type of rock and wood arrangement should be more than 2 blocks to avoid the situation of the character stuck between the terrains.
 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Redesign the terrain layout (Oct. 12)
- [x] Redesign the rocks arrangement (Oct. 14)
- [x] Redesign the rocks arrangement. (Oct. 15)
- [x] User testing on the new terrain(Oct. 16)
 
**Completion Deadline:** Oct. 19
 
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitLab Username) (Slack Handle)
- Richard (@AppleByter) (Richard Thomas)
