### ISSUE TITLE
Implement chooser GUI choice persistence and music change logic

### ISSUE THREAD

**Issue by ThatTechedGuy** [UQdeco2800/2021-ext-studio-2#416]
**Feature:**: #364 

# **Description**
To implement the GUI logic for the music selection chooser GUI. This involves creating  a reusable `BackgroundSelectionComponent` which can be added to every screen. It should be modified further to accept a `position` prop so that the component is flexible enough to align the music icon to all four corners of the screen. The component, when added to the UI `entity` of a screen, should add a music selection icon to that screen. Clicking on that icon should open a dialog which displays all the track names along with radio buttons for choice. The dialog should have a close button which makes it hide itself. On clicking on a particular radio button, that particular track music should be selected, and the choice of the user should be persisted in local storage. 
 
# **Dependencies**
- Background music (in game and for all screens) #385
- Chooser GUI Implementation #401  
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Adding JSON config with a mapping of screen names and associated background music
- [x] Making `BackgroundSelectionComponent` accept a corner `position` prop
- [x] Adding reusable `BackgroundSelectionComponent` to every screen
- [x] Extra: Refactoring and re arranging code of all screen files
- [x] Extra: Minor refactors and fixes throughout codebase
 
**Completion Deadline:** Oct. 16

# **Documentation**
- To be added

# **Member**
- Vishal Gupta (@ThatTechedGuy)
