### ISSUE TITLE
Team 3 Task Ticket 2 - Determine the show of Buffs

### ISSUE THREAD

**Issue by 7ayuu** [UQdeco2800/2021-ext-studio-2#42]
# **Description**
**Task:** [ Determine the show of Buffs ](#32 )
**Feature:** [ Team 3 Feature Ticket - Buffs/Debuffs ](#10 )

Determine the image of Buffs and the interactions with the characters created based on the style and setting of the entire game.  
 
## **Example (optional)**

- Determine the show of the Buffs 
- Combine the properties of the buffs to determine their appearance image, e.g. When the item's property is to increase defense, the image of a shield surrounding the character will appear.  
- Communicate with other teams to get a better idea of their features.

 
# **Dependencies** 
There are a few tasks that will be the dependencies of our task:
- [x] The design of the items will affect our setting of buffs. (#9 )
- [x] The set painting part of the character state will affect our design of the appearance of buffs 
 (#7 )
- [ ] Game elements, maps and perspectives (#18 )
 
# **Tasks**
Detailed task description:
- [x] #34
- [x] Task 1.2: Communicate with other teams to confirm their features for determine the data for buffs
- [ ] Task 1.3: Determine how the appearance of buffs will affect the manifestation of the character after it is acquired. 
 
# **Milestones**
List of steps that need to be completed for this task:
- [x] Task 1.1 (Aug. 19)
- [x] Task 1.2 (Aug. 19)
- [ ] Task 1.3 (Aug. 19)

**Completion Deadline:** Aug. 20

 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Aditya Samuel Hadinata(@AdityaSHadinata) 
- Zhenyu Ding (@7ayuu) 
- Zewei Zhu (@EricZhu123)  
- Wei Liu (@WeiLIU01)
