### ISSUE TITLE
Team 4 Sprint 4: Task 1 - MPC Buff/Debuff Implementation

### ISSUE THREAD

**Issue by kprohith** [UQdeco2800/2021-ext-studio-2#426]
# Description
This Task is dedicated to the integration of Buff and Debuff functionality of the protagonist. We need to take the following insights into consideration...
- Criteria for Buffs execution 
- Criteria for Debuffs execution
- How will the animation be performed.
- Where to execute buffs and Debuffs from?
Therefore, it is necessary to discuss with Team 3 to determine how it would trigger the buff and debuff effect? 

# Sub Features & Components
- Player Buff image/animation integration.
- Player DeBuff image/animation integration.

# Examples
- The player should be able to signify the effect (Buff/Debuff) it is experiencing.

# Milestones
- [ ] Code implementation of Buff launch (team 3)
- [ ] Code implementation of DeBuff launch (team 3)
- [x] Code implementation of Buff Animaiton  (team 4)
- [x] Code implementation of DeBuff Animaiton  (team 4)

**Test and evaluation deadline (Oct. 19)**

# Members

- Prateek Kumar Gupta - @prateek45
- Rohith Palakirti - @kprohith 
- Zhenyu Ding(@7ayuu )
- Yuanye Zhang(@YuanyeZhang) (Jared Zhang)
- Sumer Makhija (@sumermakhija)

**Comment by prateek45** [comment]
Changing the Ticket to Team collab between Team 3 and 4

**Comment by prateek45** [comment]
@sumermakhija @7ayuu @YuanyeZhang Please implement your buffs and debuffs function.
