### ISSUE TITLE
Team 4 Sprint 4: Task 3 - Finalise Buff and Debuff Frames of MPC

### ISSUE THREAD

**Issue by enmmjc** [UQdeco2800/2021-ext-studio-2#452]
# Description
This task ticket is to record and update the animation design of the remaining buff/debuff to ensure that all the buff effects of the main character are displayed. Some new issues we need to consider:
- Will magma burn be shown as buff or a new frame?
- How many final frames will we need for the new attack movement - related to the final buff frame count.

# Sub Features & Components
- Frames of Buff and debuff for OG attire/gold_2 attire/gold_4 attire/gold_6 attire.
- Effect of buff and debuff.

# Examples
- When the main character picks up the buff item, a corresponding buff icon will appear behind him to show the current character's status.

# Milestones
- [x] Integrate the Gold_2 attire with buff/debuff icons.
- [x] Refine the details and check the consistency with all existing action frames.
- [x] Integrate the new attack and magma burn frames with buff and debuff icons for all 4 set of attires.

**Test and evaluation deadline (Oct. 18)**

# Members
- Jiacheng Ni - @RecklessPotcover (Alex)
- Jescy Xu - @enmmjc 
- Yingxin Liu - @LIU-Evelyn
