### ISSUE TITLE
Team 4 Sprint 4: Task 4 - Design Burn Frame for Magma Collision

### ISSUE THREAD

**Issue by enmmjc** [UQdeco2800/2021-ext-studio-2#453]
# Description
This task ticket is to design the burning effect of the main character after touching the magma. In order to achieve this design, we need to think about the following points: 
- Is the effect of the character touching the magma changing the action or just changing the appearance?
- How many frames need to be drawn to complete the animation design?
- Combine the designed burning appearance with the existing buff/debuff effects.
These points will be resolved by communicating with team 6 during the design process.

# Sub Features & Components
- Burn sprites - The burning effect of each action used in the game. 
- Animation integration of character burning effect and buff/debuff effect.

# Examples
- When the main character is in contact with magma, the burning effect will be displayed regardless of whether there is buff on the character at this time.

# Milestones
- [x] Consider the burning effect for magma collision
- [x] Design the burning effect of original attire 
- [x] Design the burning effect of gold_2 attire
- [x] Design the burning effect of gold_4 attire
- [x] Design the burning effect of gold_6 attire
- [x] Integrate the burning effect of all attires with the existing buff/debuff effect

**Test and evaluation deadline (Oct. 18)**

# Members
- Jiacheng Ni - @RecklessPotcover (Alex)
- Jescy Xu - @enmmjc 
- Yingxin Liu - @LIU-Evelyn

**Comment by RecklessPotcover** [comment]
**_Created a frame of Jason burning, also 9 extended frames with buff_**

![main_player_burn_1](https://user-images.githubusercontent.com/31987631/137699045-ea5e719e-f40a-4858-a0da-791d4ff1a07d.png)

![main_player_burn_dizzy_1](https://user-images.githubusercontent.com/31987631/137699227-978f688c-fa0c-477b-bb56-4251236463bd.png)

![main_player_burn_health-down_1](https://user-images.githubusercontent.com/31987631/137699248-ceaed736-4b5c-4fb9-bd04-a3d4bc713aa6.png)

![main_player_burn_health-limit-up_1](https://user-images.githubusercontent.com/31987631/137699277-69c56183-75b4-49d5-9f0e-5f434e5aa709.png)

![main_player_burn_health-up_1](https://user-images.githubusercontent.com/31987631/137699323-b8cd482c-caae-46f2-b24e-cf8dd3114a40.png)

![main_player_burn_hungry_1](https://user-images.githubusercontent.com/31987631/137699338-986f573f-1ad8-4cd8-aff3-1159930343ce.png)

![main_player_burn_poisoned_1](https://user-images.githubusercontent.com/31987631/137699359-a094e981-f63a-4e26-a8ac-e4e8a0847050.png)

![main_player_burn_recovered_1](https://user-images.githubusercontent.com/31987631/137699391-f6b8f9bc-0660-4e5c-9d44-e255ce283e05.png)

![main_player_burn_speed-down_1](https://user-images.githubusercontent.com/31987631/137699423-681d87dc-898b-408d-aa26-8244e0f6d7fc.png)

![main_player_burn_thirsty_1](https://user-images.githubusercontent.com/31987631/137699451-291081d5-b964-4fd2-a2c4-f19447994eb0.png)

**Comment by LIU-Evelyn** [comment]
**Created a frame of Jason burning, also 9 extended frames with buff - Gold_2 attires:**
![main_player_burn_recovered_1](https://user-images.githubusercontent.com/88132643/137705971-1f3b5c48-114a-441a-8534-967561d2cd8d.png)
![main_player_burn_poisoned_1](https://user-images.githubusercontent.com/88132643/137705979-0a5b960a-b44b-4bde-8b74-2e2e30fd7351.png)
![main_player_burn_hungry_1](https://user-images.githubusercontent.com/88132643/137705981-9c463a97-0365-4d69-b6b2-f95f3615dc8f.png)
![main_player_burn_health-up_1](https://user-images.githubusercontent.com/88132643/137705984-293f6f18-ca6d-4923-bc06-8d29cd51a295.png)
![main_player_burn_health-limit-up_1](https://user-images.githubusercontent.com/88132643/137705989-e4399ca4-51ee-4727-8424-bfea58f3c1e9.png)
![main_player_burn_health-down_1](https://user-images.githubusercontent.com/88132643/137705993-81db15dc-5b58-428c-bdbc-217f406967d6.png)
![main_player_burn_dizzy_1](https://user-images.githubusercontent.com/88132643/137705998-f6d4c274-dcb7-4591-866e-30f231de925d.png)
![main_player_burn_1](https://user-images.githubusercontent.com/88132643/137706006-1e116683-95a7-4d4f-833d-55ff1e536bb9.png)
![main_player_burn_thirsty_1](https://user-images.githubusercontent.com/88132643/137706011-05c552a1-bb0a-4e8b-8e43-393e14b1fd86.png)
![main_player_burn_speed-down_1](https://user-images.githubusercontent.com/88132643/137706023-827b67b4-1a8f-46c2-8761-a3eee1d4b806.png)
