### ISSUE TITLE
Team 5 Task Ticket 1 - Design of inventory system

### ISSUE THREAD

**Issue by TerrestrisYE** [UQdeco2800/2021-ext-studio-2#46]
# **Description**
**Task:** [Design of inventory system](#3).
**Feature:** [Bag System/Inventory](#2)
 
Discuss and design the requirements, usage and artistic style of the basic inventory system.

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Determination of the basic form of the inventory system
- [x] Determination of common attributes of inventory system (size and partition)
- [x] Preliminary design of inventory system layout
- [x] Determination of the artistic style of the inventory system
- [ ] Prototype implementation of inventory system
 
**Completion Deadline:** Aug. 23
 
e.g.
- [x] Discuss with Team 2 to determine the player’s inventory system style.
- [x] Discuss with Team 7 to determine the form of interaction between the achievement system and the backpack.
- [x] Build a basic layout prototype
- [x] Design artistic style for layout and improve prototype
 
# **Documentation**
None
 
# **Member**
- YE Lingfeng (TerrestrisYE) Lingfeng YE
- LIU Yiting (Khassar0) khassar
- Xinkai Tang (Kai9613) Xinkai.tang
- Sumer Makhija (sumermakhija) Sumer Makhija
- Yuang Zhang (yu-ang-zhang) yuang zhang
