### ISSUE TITLE
UI Optimization of propStore

### ISSUE THREAD

**Issue by LiwenJin2829** [UQdeco2800/2021-ext-studio-2#466]
# **Description**
**Task:**  UI Optimization of Props Store
**Feature:** [props store](#158 )

We will enrich the background of the prop store in this sprint. We will design a pixel style background that meets the design criteria and add more "shopping" elements. The goal is to improve the prop store interface and improve the purchase experience in the game.

## **Example**
- **Pixel style shelf**: In the last sprint, we have designed the shelf, but it does not conform to the design style of the game. Therefore, in this sprint, we designed a new pixel style shelf to maintain the consistency of the design.
- **Cash register**: The cash register can easily remind players of "purchase", so we can add this element to emphasize the role of props store.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Group discussion on props store improvement scheme(Oct. 06)
- [x] Element collection and brainstorming (Oct. 09)
- [x] Graphic Design of Props Store (Oct. 15)
- [x] Implement the Props Store UI coding (Oct. 17)
- [ ] Wiki Documentation & User Tests (Sep. 18)
 
**Completion Deadline:** Oct.19

# **Documentation**
- [Props Store UI Design](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Props-Store-UI-Design)
- [Prop store layout(updated)](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Prop-store-layout)
