### ISSUE TITLE
Randomising Item drops

### ISSUE THREAD

**Issue by LiwenJin2829** [UQdeco2800/2021-ext-studio-2#467]
# **Description**
**Task:**  Randomising Item drops
**Feature:** [Items that the player can pick up](#9)
In sprint 4, we will polish the function of "Randomising Item drops". When playing, different items may drop on the map so that players can pick them up and gain different buff effects.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Group discussion on props store improvement scheme(Oct. 06)
- [x] Graphic Design of items Store (Oct. 15)
- [x] Implement the randomising item drops coding (Oct. 17)
- [x] Wiki Documentation (Oct. 18)
 
**Completion Deadline:** Oct.19

# **Dependencies**
- **Buffs and Debuffs**: the items have buffs and debuffs effects which need to be discussed with Team 3 (#10) 

# **Documentation**
- [Pickable Items](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Pickable-Items)
