### ISSUE TITLE
Adding new items to the Props Store

### ISSUE THREAD

**Issue by LiwenJin2829** [UQdeco2800/2021-ext-studio-2#469]
# **Description**
**Task:**  Adding new items to the Props Store
**Feature:** [props store](#158 )
In the last sprints, we had two items in props store——food & heart. To increase the fun of game and enrich the props store, in sprint 4, we will add more buffs on different Items.

New props:
-Water: Restore the thirsty value, $2
-More items (We need to add more effects on related items. The effect of the specific buff depends on team 3.)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Group discussion on props store improvement scheme(Oct. 06)
- [x] Graphic Design of props  (Oct. 15)
- [x] Implement the coding (Oct. 17)
- [x] Wiki Documentation (Oct. 18)
 
**Completion Deadline:** Oct.19

# **Dependencies**
- **Buffs and Debuffs**: the items have buffs and debuffs effects which need to be discussed with Team 3 (#10) 

# **Documentation**
- [Props design](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Props-design#props)
