### ISSUE TITLE
Team 5 Task Ticket 2 - implement of bag system

### ISSUE THREAD

**Issue by yu-ang-zhang** [UQdeco2800/2021-ext-studio-2#47]
# **Description**
**Task:** [implement of bag system](#3).
**Feature:** [Bag System/Inventory](#2)
 
Implementation the features and properties of bag system. The bag has a capacity. Player can store, use or remove things from bag.

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Determination of the basic form of the bag system
- [x] Determination of properties of bag system 
- [x] Determination of features of bag system 
 
**Completion Deadline:** Aug. 23
 
e.g.
- [x] conducting a bag class
- [x] conducting a baginterface class
- [x] conducting a componentintecafe class

 
# **Documentation**
None
 
# **Member**
- YE Lingfeng (TerrestrisYE) Lingfeng YE
- LIU Yiting (Khassar0) khassar
- Xinkai Tang (Kai9613) Xinkai.tang
- Sumer Makhija (sumermakhija) Sumer Makhija
- Yuang Zhang (yu-ang-zhang) yuang zhang

**Comment by Bohan-is-in-the-zone** [comment]
I add few lines in your bag system class: plus 10 bonus points every time when player pick up something. 
However, in the game I don't think player can pick anything. I added anyway.

**Comment by Bohan-is-in-the-zone** [comment]
#151 please approve this.
