### ISSUE TITLE
Hunger - debuff when player have no 'food' resource

### ISSUE THREAD

**Issue by YuanyeZhang** [UQdeco2800/2021-ext-studio-2#470]
# **Description**
**Task:** [Hunger-buff&debuff](#3).
 
a "debuff" when player have no food. 
Due to the difficulty of the game, after talking with group3 who designing "buff & debuff", we decided to make the existing hunger no longer a debuff, but a gain buff.  If the player's current HP is not 100 (max), Player increase health per second when he have no food, and the gain buff stops when he picks up new 'food' or he is already full of HP.
 
 
# **Dependencies**
- [x] food&water system (#122 )

 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Code development (Oct. 18)
- [x] test code (Oct. 19)
- [x] wiki doc(Oct .19)

 
# **Documentation**
- [WIKI]https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Hunger-and-Thirst
- ...
 
# **Member**
- Yuanye Zhang (@YuanyeZhang ) (YuanyeZhang)
