### ISSUE TITLE
User Testing for items & props

### ISSUE THREAD

**Issue by LiwenJin2829** [UQdeco2800/2021-ext-studio-2#472]
# **Description**
**Task:**  User Testing for items & props
**Feature:** [props store](#158 ), [Items that the player can pick up](#9)

In sprint 4, we optimized items drop and props store based on previous user feedback. Here we do user testing again. On the one hand, we need to verify whether the new design and functions are effective. On the other hand, we want to look for new promotion opportunities.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Group discussion on props store improvement scheme(Oct. 06)
- [x] Set goals for the user testing (Oct. 09)
- [x] User testings(Oct. 15)
- [x] Evaluation (Oct. 17)
- [x] Wiki Documentation(Oct. 18)
 
**Completion Deadline:** Oct.19

# **Documentation**
- [Randomised Item Drops](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Items-testing)
- [Buying Props User Testing](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Buying-Props-User-Testing)
