### ISSUE TITLE
thirst and hunger icon display

### ISSUE THREAD

**Issue by YuanyeZhang** [UQdeco2800/2021-ext-studio-2#474]
# **Description**
**Task:** [buff/debuff icon display in mainmemu](#3).
 
The hunger icon and thirst icon display in main menu screen when player have no water/food and disappeare when player pick a new one.
 
# **Dependencies**
- [x] food&water system (#122 )

 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Code development (Oct. 18)
- [x] test code (Oct. 19)
- [x] wiki doc(Oct .19)

 
# **Documentation**
- [WIKI]https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Hunger-and-Thirst
- ...
 
# **Member**
- Yuanye Zhang (@YuanyeZhang ) (YuanyeZhang)
