### ISSUE TITLE
Team 6 Feature ticket- Infinite loop game

### ISSUE THREAD

**Issue by katrinafu1** [UQdeco2800/2021-ext-studio-2#5]
# **Description**
The game will be in an infinite loop environment. It will continue until the player is dead or running out of HP. The infinite loop game environment will mainly depend on the character's HP and the storyline missions. As the player is able to keep playing the game until he/she dies, the scoring system and the storyline mission will keep running. Also, the UI design of the game background will change according to the game status and the player status. When the player is dead, the scoring system will stop and there will be a 5 seconds countdown to let the player choose whether to stop the game and back to the main menu or keep playing.
 
## SubFeature/component (optional)
Game background and environment UI design
Infinite loop coding conditions
Combining with the other game features
Game over screen design

 
## **Examples (optional)**

1)  After the user ends the game or dies, there will be a prompt box to remind the user to die or restart, and there will be a five-second countdown to automatically restart the game.
2) When the five-second countdown is in progress, you can choose to restart or end the game. After the five-second countdown, the player automatically enters to continue the game.
Benefits: Players can choose whether to continue the game or end the game. The prompt box and countdown are designed in this way, and the choice is up to the player, which can improve the player's ability.
3) Game over screen will be in black and white colour, when the player is dead, the environment will change from multicolour to black and white.

# **Dependencies**
 Character status and player status(Team2): Determine the UI of the game visual background, also the character's health bar.
 Storyline and mission(Team 7): Determine how the player completes the game loop.
Score(Team 9): Display the player's score in the end window after the player finishes the game.
 
 

 
# **Milestones**
- [x] Goal 1: Designing the UI of the game environment and background (Aug. 20) 
- [x] Goal 2: Implement the environment and combine it with the character's health point and the storyline features(Aug. 23)
- [x] Goal 3: Design the game over screen and confirm the camera view
- [x] Goal 4: Finalising the coding of the infinite loop by combining the other game features (Aug. 26)
- [x] Goal 5: Combining the UI game environment design and the coding (Aug. 28)
 
**Completion Deadline:** Aug. 30
 
# **Extras (optional)**
- [x] Extra components that you may implement if you get time.
- [x] ...
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [User documentation](../../wikis/Game-Guide#section1)
- ...
 
# **Members**
- Yinghao Fu (katrinafu1) (Katrina Fu)
- Yuqi Yang (Marco777777) (Yuqi Yang)
- Anh Duy Hoang (EvansH1997) (Anh Duy Hoang)
- Jingxin Liu (JingXinNN) (Jingxin Liu）
- Zi Yang (yzy98) (Zi Yang)

**Comment by uqtnieva** [comment]
Looks good! 

Double-checking: is your team covering the game over screen as well?

**Comment by Bohan-is-in-the-zone** [comment]
Score(Team 9): Determination of whether or not the player has lost the game depends on the score of the player.
This is a good idea but team 9 only handles for displaying the score after the game. This feature can be implemented in the later sprints I guess. And team 9 will also implement a clock to record the gaming time.

**Comment by katrinafu1** [comment]
> Score(Team 9): Determination of whether or not the player has lost the game depends on the score of the player.
> This is a good idea but team 9 only handles for displaying the score after the game. This feature can be implemented in the later sprints I guess. And team 9 will also implement a clock to record the gaming time.

Hi,  the final score of the player will display on the game over the UI screen, so that's why we add the scoring system in our dependencies.

**Comment by kprohith** [comment]
Are you implementing the pathway(s) for the player to move on?

**Comment by katrinafu1** [comment]
> Are you implementing the pathway(s) for the player to move on?

Yes

**Comment by kprohith** [comment]
> 
> 
> > Are you implementing the pathway(s) for the player to move on?
> 
> Yes

By when is the pathway implementation expected to be ready?

**Comment by katrinafu1** [comment]
> > > Are you implementing the pathway(s) for the player to move on?
> > 
> > 
> > Yes
> 
> By when is the pathway implementation expected to be ready?

We have already finished the terrain but still figuring out how to change the camera angle, will be committing the terrain tonight.

**Comment by kprohith** [comment]
> 
> 
> > > > Are you implementing the pathway(s) for the player to move on?
> > > 
> > > 
> > > Yes
> > 
> > 
> > By when is the pathway implementation expected to be ready?
> 
> We have already finished the terrain but still figuring out how to change the camera angle, will be committing the terrain tonight.

Can you give us an update on Discord as soon as it is complete? We need the pathway to finish integrating the character.

**Comment by lisslulay** [comment]
Hello, I am from team 8, and we found that you have generated many walls and stones on the map. I have cancelled their attack attributes.

We recommend that you cancel these components, because they essentially do not provide additional map routes, but block the player, so they belong to obstacles. At the same time, it has many bugs, such as making the player stuck somewhere. Also, team8 is in In sprint2, we hope to implement attack elements from the sky. These walls and stones will hinder the attack, that is, help the player avoid the attack.

If you definitely want to make some obstacles, it is recommended that you design the pits on the ground, because only you can do this. Maybe you can consider dealing with the bug that characters will fall to the ground, or you can consider UI design, such as on the road Add flowers and plants that will not block the player and the background of the game.

Wall and stone did interfere with the design of the obstacles group. If you really want to keep it, can you reduce the number of it? Team 8 is grateful.

**Comment by yzy98** [comment]
> Hello, I am from team 8, and we found that you have generated many walls and stones on the map. I have cancelled their attack attributes.
> 
> We recommend that you cancel these components, because they essentially do not provide additional map routes, but block the player, so they belong to obstacles. At the same time, it has many bugs, such as making the player stuck somewhere. Also, team8 is in In sprint2, we hope to implement attack elements from the sky. These walls and stones will hinder the attack, that is, help the player avoid the attack.
> 
> If you definitely want to make some obstacles, it is recommended that you design the pits on the ground, because only you can do this. Maybe you can consider dealing with the bug that characters will fall to the ground, or you can consider UI design, such as on the road Add flowers and plants that will not block the player and the background of the game.
> 
> Wall and stone did interfere with the design of the obstacles group. If you really want to keep it, can you reduce the number of it? Team 8 is grateful.

Hi there, we are planning to pile up stones and woods in Sprint 2. Just like what mentioned [here](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Terrains). In this case, stones will not prevent attack from the sky.

**Comment by lisslulay** [comment]
> > Hello, I am from team 8, and we found that you have generated many walls and stones on the map. I have cancelled their attack attributes.
> > We recommend that you cancel these components, because they essentially do not provide additional map routes, but block the player, so they belong to obstacles. At the same time, it has many bugs, such as making the player stuck somewhere. Also, team8 is in In sprint2, we hope to implement attack elements from the sky. These walls and stones will hinder the attack, that is, help the player avoid the attack.
> > If you definitely want to make some obstacles, it is recommended that you design the pits on the ground, because only you can do this. Maybe you can consider dealing with the bug that characters will fall to the ground, or you can consider UI design, such as on the road Add flowers and plants that will not block the player and the background of the game.
> > Wall and stone did interfere with the design of the obstacles group. If you really want to keep it, can you reduce the number of it? Team 8 is grateful.
> 
> Hi there, we are planning to pile up stones and woods in Sprint 2. Just like what mentioned [here](https://github.com/UQdeco2800/2021-ext-studio-2/wiki/Terrains). In this case, stones will not prevent attack from the sky.

The characters now move forward automatically. Your idea of ​​placing the grid may come from Mario, but that is a different game mechanism.

First of all, the complex terrain is not suitable for automatic advancement games. The reason why Mario can have other roads on the ground is that it is controlled by the player whether to advance. However, in the game of ours, it advances automatically, and the player has to face obstacles or enemy attacks. It will be difficult to face many stones and woods.

Second, the player has very little time to react. Players occupy a large proportion of the map, which is another difference from Mario, that is, the front ground and obstacles that players can see are not many. They need to react immediately and don't have time for thoughtful strategic responses.

Finally, terrain design should also consider other components on the map. If there are no obstacles or enemies, your terrain may be good, but after adding obstacles, it becomes very chaotic. This game has a special obstacle group, which means that the emergence of obstacles is inevitable. Imagine that in the terrain you designed, the red ones are obstacles or enemies that will launch attacks, which makes the game interface very messy.
![image](https://user-images.githubusercontent.com/78423568/132083754-fec51f9b-47e7-4be7-b1c8-2febc27f7e3b.png)

Sincerely hope that you can consider these issues.

team 8

**Comment by lisslulay** [comment]
In the future, there are not only obstacles, enemies, but also things that can be picked up on the road. This is an interface without wood and stone, which already has many elements.
![image](https://user-images.githubusercontent.com/78423568/132084466-fb0cc86d-b939-4982-9091-58c01aa74a15.png)

We very much hope that you can try the UI design, a good-looking interface will make the game look a lot more attractive. team 8

**Comment by yzy98** [comment]
> In the future, there are not only obstacles, enemies, but also things that can be picked up on the road. This is an interface without wood and stone, which already has many elements.
> ![image](https://user-images.githubusercontent.com/78423568/132084466-fb0cc86d-b939-4982-9091-58c01aa74a15.png)
> 
> We very much hope that you can try the UI design, a good-looking interface will make the game look a lot more attractive. team 8

So the best solution is deleting woods and rocks right? If that will help, our team is happy to delete rocks and woods :)

**Comment by lisslulay** [comment]
> > In the future, there are not only obstacles, enemies, but also things that can be picked up on the road. This is an interface without wood and stone, which already has many elements.
> > ![image](https://user-images.githubusercontent.com/78423568/132084466-fb0cc86d-b939-4982-9091-58c01aa74a15.png)
> > We very much hope that you can try the UI design, a good-looking interface will make the game look a lot more attractive. team 8
> 
> So the best solution is deleting woods and rocks right? If that will help, our team is happy to delete rocks and woods :)

Thank you very much for considering our questions. This picture is used as a reference for your team's designers. There are indeed many problems with stone and wood, but how to do it is up to your team to discuss and decide. Our suggestions are based on our team's features, but at the same time, we don't want to destroy the results of your hard work. You have complete decisions about what the map will eventually develop into. We accept all the choices you make after thinking about these issues.
Thanks.
Team 8
