### ISSUE TITLE
Team-1 Task Ticket Items UI Design

### ISSUE THREAD

**Issue by LiwenJin2829** [UQdeco2800/2021-ext-studio-2#51]
# **Description**
This task is to design the pickable items for sprint 1. 

## **Examples**
- **Food/Water**: The player can pick up food/water to recover.

# **Dependencies**

# **Milestones**

- [ ] Determine the type and function of items (Aug. 20)
- [ ] Determine the icon size, design guidelines, color (Aug. 23)
- [ ] Design items (Aug. 26)
- [ ] Design walkthrough (Aug. 28)

**Completion Deadline:** Aug. 30

# **Documentation**
- [Main description of feature](../../wikis/page1)
- [User documentation](../../wikis/Game-Guide#section1)

# **Members**
- Liwen Jin (@LiwenJin2829 )
