### ISSUE TITLE
Team-2 Feature Ticket-Character Status/Player Status

### ISSUE THREAD

**Issue by YuanyeZhang** [UQdeco2800/2021-ext-studio-2#7]
# **Description**
This feature gives different statuses to the characters in the game. Our current concept is for the player to get different statuses as the game progresses, either negative or positive. These states also can be passive(injury) or active(tired) which can be interpreted as an additional task, like hunger means the player needs to get food. If you are poisoned, you may need to look for medicine. 

Additionally, players may be rewarded for random events, to get some positive/negative status. 

## SubFeature/component (optional)
If the ticket contains multiple components, you should explain them in more detail here.

## **Examples (optional)**
The type of player status depends on the current player's environment and triggered events

If the player is in a swamp environment, the player will speed up the consumption of physical strength and will be added with slow-moving debuffs. When the player chooses to use a specific potion, these debuffs can be eliminated.

If the player encounters a snowy day, the player may be affected by the "cold" state and the movement speed will be limited

# **Dependencies**
 
Status based on Buffs/Debuffs - Team 3 (the influence of different buffs/ debuffs the players got)
Status based on Main Character Player - Team 4 (which status it displays depends on where and what the player is doing)
Status based on Bag System/Inventory - Team 5 (the specific potion can be pick up from the bag system)
 
# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Implement algorithm for status condition---e.g. Players need to eat once within 30 seconds(Aug. 20)
- [ ] Implement the effect of this status---e.g. speedup/slow down(Aug. 23)
- [ ] Implement ways for the player to cancel special states---conditions(get foods. complete a mission)  (Aug. 26)
- [ ] Implement the effect back to original (Aug. 28)

# **Extras (optional)** 
- [ ] Extra components that you may implement if you get time.
- [ ] ...

# **Documentation**
- [Main description of feature](../../wikis/page1)
- [User documentation](../../wikis/Game-Guide#section1)
- ...
 
# **Members**
- Name (GitLab Username) (Slack Handle) -- only one is needed if they are the same.
- Yuanye Zhang(@YuanyeZhang) (Jared Zhang)
- He Zhu(@GavintheLionHeart ) (He Zhu)

**Comment by lisslulay** [comment]
Hi, Do you have the intention to implement the function of reducing health? #14 would like to call reducing health and speed function.
Another question: does the position of the character is included in character status?

**Comment by uqtnieva** [comment]
Hey! Great start. 

I think it would be good to start thinking about how a player can lose the game (GAME OVER) e.g. If they don't eat every 30 seconds, they might lose health (and include this in the feature ticket) AND how this will look on the game: will it be displayed as a bar or hearts? 

For your feature, it would be good to communicate with team 5 who are doing the world generation/ending screen and team 3 who are covering buffs/debuffs.

There seems to be some overlap with team 3 as to who is implementing the buffs/debuffs (writing the code to slow the character down, etc).

**Comment by uqtnieva** [comment]
> Looks good!
> 
> Double-checking: is your team covering the game over screen as well? This might be something you consider giving to Team 2 since they are taking on the player's status/health bar.

**Comment by YuanyeZhang** [comment]
> On team 6's ticket #5 :
> 
> > Looks good!
> > Double-checking: is your team covering the game over screen as well?

**Comment by YuanyeZhang** [comment]
To avoid overlapping with team3, we have made some updates

**Comment by lisslulay** [comment]
Hi, I just found out that you used setRemoveTexture().  I'm so sorry, this method was originally written for obstacles, and I didn't mark it out very clearly. You should be able to find that this method will remove the texture component every time the game is updated. Obstacles use it because obstacles will be removed immediately. If the character uses it, the texture will be removed every time it is updated. I don't know if this will cause problems such as memory usage. Maybe you can try to write a separate method to achieve the purpose of removing texture. 
Team 8
![image](https://user-images.githubusercontent.com/78423568/131467799-df8f6fc8-4bad-4a46-829a-ad2613c61fac.png)
