### ISSUE TITLE
Team-5 Feature Ticket: Bag System/Inventory

### ISSUE THREAD

**Issue by TerrestrisYE** [UQdeco2800/2021-ext-studio-2#8]
# **Description**
**Task:** [Implement Bag/Inventory System](#3).
**Feature:** [Bag System/Inventory](#2)
 
The Inventory system will allow players/characters to hold found items with following features: backpack, equipment bar and quick bar. Methods for moving, discarding, and using item will be included.

The storage method of the item will have the following attributes:

- Items will be stored in limited space by means of metering slots or weight (or both).
- Multiple storage spaces can be provided, including an equipment slot with item effective capabilities, a main backpack, and a quick backpack that is convenient for players to use the main backpack items. (**Abandoned**)
- Item bar
- Contains methods for manipulating the items in the backpack and it's properties. Players/characters can obtain, put down, use, arrange the items in the backpack and change the properties of the backpack (e.g. backpack capacity).
 
## **Example**
 - Part1: Players can pick up items through the map and carry them to the storage space of the backpack
Benefits: Items that are acquired in other ways during the course of the game will be stored in quantities in the pack, and the pack will be sized by quantity or weight.
 - Part2: Players can view the contents of the backpack at any time, and set the gear slot for quick items
Benefits: Players can set up slots for different quick items. When items run out, players can replace them. For example, when the player is injured and needs to quickly use items to recover, there is no need to fully open the backpack to search for items. In addition, backpack items will not be lost. Unless the user actively throws and drops the backpack.
 - Part3: The number of items in the backpack can be changed by user behavior:
Benefits: Players will be able to make data changes by cleaning their backpacks and discarding items. There are three ways to change inventory: use, discard, and obtain.
 
# **Dependencies**

 
- [x] Dependency 1 (#9 )
 
e.g.
- [x] The number, level, and type of items needed to be picked up.

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 - Design the specific functions of the inventory system
- [x] Step 2 - Build basic prototypes and framework prototypes
- [x] Step 3 - Prototype testing and improvement
- [x] Step 4 - Implement code according to requirements
- [x] Step 5 - Testing and evaluation funcational module
 
**Completion Deadline:** Sprint 1
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- YE Lingfeng (TerrestrisYE) Lingfeng YE
- LIU Yiting (Khassar0) khassar
- Xinkai Tang (Kai9613) Xinkai.tang
- Sumer Makhija (sumermakhija) Sumer Makhija
- Yuang Zhang (yu-ang-zhang) yuang zhang

**Comment by uqtnieva** [comment]
Hey! I would recommend sorting out with team 1 about who is implementing the "pick up" item mechanic: team 6 or team 1? 

Both of your teams have mentioned it in your tickets. 

Looks good so far.

**Comment by TerrestrisYE** [comment]
> Hey! I would recommend sorting out with team 1 about who is implementing the "pick up" item mechanic: team 6 or team 1?
> 
> Both of your teams have mentioned it in your tickets.
> 
> Looks good so far.

Hi, we are not doing the pickup feature on our own, but we will provide the method to add/use items to the backpack.

**Comment by katrinafu1** [comment]
Hi team5, Could you please check the new feature ticket about the prop store of the team1? We need to save the total coins of the previous game that have been collected, so the player can buy the props next time. Can you guys do the save total coins function as you guys are implementing the storage system? Thanks!
