### ISSUE TITLE
Team9 Sprint 2 Feature Ticket: Scoring System Updated

### ISSUE THREAD

**Issue by Bohan-is-in-the-zone** [UQdeco2800/2021-ext-studio-2#99]
# **Description**
1. In sprint 2, the scoring system will add achivement bonus score to our score calculation. And also relates to the items that player picks up (the items in the bag system)

2. There is also a small update about the timer UI, we are trying to implement that using gif to make it more beautiful. (Optional)

This sprint: 
1. Scoring calculation: Final Score = Time in seconds + achievment scores + Item number * 5 

# **Dependencies**
team 7 #137 ,team 5 bag system #40 
 
 
# **Milestones**
- [x] Work with team 7 about their bonus scores. 9/8/2021
- [x] Start implementing team 5 stuff. 11/9/2021
- [ ] Polish the scoringSystem class.  (If we still have time, we would like to use a GIF to represent the game clock) 13/9/2021
 
**Completion Deadline:** (Date)
 11 September 
 
# **Members**
(Git hub name)(Slack name)
- @Bohan-is-in-the-zone (Bohan Xu)
- @YiYang200 (Yi Yang)
- @Noarrrr (Keyu Bai)
- @yungseop (YoungSeob Lee)
- @pranavdhoolia (Pranav Dhoolia)

**Comment by uqtnieva** [comment]
Please include the list of dependencies and how your feature is dependent on them and include dates for the milestones. Your description is also not entirely clear.

**Comment by Bohan-is-in-the-zone** [comment]
@uqtnieva Updated.

**Comment by lisslulay** [comment]
Hi, hello, we are team8. We have a question about scoring. The current scoring method is that the longer the survival time, the higher the score.

This means that when a character runs up, it is more difficult to get a high score than when he walks. Because in the same time, running mode needs to face more obstacles than walking mode. Slowing down or stopping in a certain place is the easiest way to get points. In this way, the slowdown helped the character.

However, the theme of the game is doomsday racing, or our understanding is doomsday escape. Should the escape game be calculated based on the distance between the character and the initial position (the character's x coordinate)?

**Comment by Bohan-is-in-the-zone** [comment]
@lisslulay yeah, that's a good point. The scoring system was implemented in sprint 1. And that moment, there are not so many obstacles. And about this "Slowing down or stopping in a certain place is the easiest way to get points. In this way, the slowdown helped the character.", team 6 in sprint 1 are doing the infinite game loop. They made the screen move automatically. I think your question can be solved by when player is slow down or stuck by an obstacle. The screen is still moving, when player is out of the game area, he will die.

**Comment by Bohan-is-in-the-zone** [comment]
@lisslulay we can definitly discuss about this next studio. So this might be a new feature about the game. There are only four days left in sprint2. Our team need to make sure we finish our planned feature first. Sorry about that. 😅

**Comment by lisslulay** [comment]
@Bohan-is-in-the-zone 
Don't worry, we just provide a reference idea, and it will be good to consider this issue in the next sprint. 😂

**Comment by Bohan-is-in-the-zone** [comment]
Wait for some help about the animation clock
